### ISSUE TITLE
time input error in Firefox52

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2826] opened 2017-07-20 07:40 UTC
v1.1.2-515-gaa681eb

![time](https://user-images.githubusercontent.com/23101283/28406126-c9b0c7e2-6d61-11e7-86c1-4f73a7f0d623.PNG)

**Comment by steven-zou** [comment] 2017-07-25 08:56
Raise issue to Clarity team

**Comment by steven-zou** [comment] 2017-08-03 08:57
@pengpengshui 

  Please do some investigation, if the issue is caused by the 'date' component itself, we can raise issue to the Clair team then

**Comment by steven-zou** [comment] 2017-08-03 10:14
Firefox does not support <input type="time" >, please refer https://www.w3schools.com/html/html_form_input_types.asp .

As it's limitation of browser itself, close this issue.

**Closed by steven-zou** 2017-08-03 10:14 UTC
Labels: area/ui, kind/bug, priority/low, UI/tmp/PFH
