### ISSUE TITLE
LDAP authentication is not working

### ISSUE THREAD

**Issue by biolounge** [vmware/harbor#2373] opened 2017-05-24 14:38 UTC
After upgrading Harbor 0.5.0 to 1.1.1, LDAP authentication is not working.

Harbor.cfg LDAP settings:

auth_mode = ldap_auth
ldap_url = ldap://myldap.server.com:389
ldap_searchdn = CN=read-user,OU=Site Roles,OU=JPCOREST,OU=COD,DC=cod1,DC=emi,DC=server,DC=com
ldap_search_pwd = password
ldap_basedn = OU=Users,OU=JPCOREST,OU=COD,DC=cod1,DC=emi,DC=server,DC=com
#ldap_filter = (objectClass=person)
ldap_uid = uid
ldap_scope = 3
ldap_timeout = 5

UI.log:

May 24 16:25:46 172.18.0.1 ui[17364]: 2017-05-24T14:25:46Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is ldap_auth
May 24 16:25:46 172.18.0.1 ui[17364]: 2017-05-24T14:25:46Z [DEBUG] [ldap.go:143]: one or more ldapFilter: (uid=usr8723)
May 24 16:25:46 172.18.0.1 ui[17364]: 2017-05-24T14:25:46Z [DEBUG] [ldap.go:395]: LDAP search errorLDAP Result Code 1 "Operations Error": 000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1
May 24 16:25:46 172.18.0.1 ui[17364]: 2017-05-24T14:25:46Z [WARNING] ldap search fail: LDAP Result Code 1 "Operations Error": 000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1
May 24 16:25:46 172.18.0.1 ui[17364]: 2017-05-24T14:25:46Z [DEBUG] [authenticator.go:71]: Login failed, locking usr8723, and sleep for 1.5s

Can someone helps us to fix this issue?

Docker version:   17.05.0-ce
docker-compose version 1.9.0

**Comment by ywk253100** [comment] 2017-05-25 03:42
@biolounge What kind of LDAP software do you use? Is the ldap_search_pwd blank? And does the Harbor 0.5.0 work well with the exactly the same configurations?

**Comment by biolounge** [comment] 2017-05-25 06:27
@ywk253100, ldap_search_pwd is not blank. LDAP authentication was working well with same configurations on Harbor 0.5.0.

**Comment by ywk253100** [comment] 2017-05-25 07:33
@biolounge I notice that there is a new line in your ldap_searchdn, does it also exist in harbor.cfg?

**Comment by biolounge** [comment] 2017-05-25 08:07
No, ldap_searchdn is in a single line in our harbor.cfg

**Comment by roldancer** [comment] 2017-05-25 09:42
@biolounge the bind password has any special character? with 1.1.1.RCx we had some problems with special characters only in the web console, with docker login was working properly.

**Comment by biolounge** [comment] 2017-05-25 10:01
@biolounge, the bind password contains a question mark(?). Do you think it could be the problem?

**Comment by roldancer** [comment] 2017-05-25 13:17
@biolounge in our case we had problems with "+" and ";" characters.

**Comment by ywk253100** [comment] 2017-05-26 02:30
@biolounge We can not reproduce your issue, please provide more information to help us find what is going wrong:
1. What version of Harbor are you using, 1.1.1 or 1.1.1.RCx?
2. What kind of ldap software are you using?
3. Paste the content of common/config/adminserver/env and /data/config/config.json files.

**Comment by biolounge** [comment] 2017-05-26 08:30
@ywk253100, We are using Harbor 1.1.1 and ldap software is openldap.


# common/config/adminserver/env

LOG_LEVEL=debug
EXT_ENDPOINT=http://docker-registry.domain.com
AUTH_MODE=ldap_auth
SELF_REGISTRATION=off
LDAP_URL=ldap://myldap.server.com:389
LDAP_SEARCH_DN=uid=read-user,OU=Site Roles,OU=JPCOREST,OU=COD,DC=cod1,DC=emi,DC=server,DC=com
LDAP_SEARCH_PWD=password
LDAP_BASE_DN=OU=Users,OU=JPCOREST,OU=COD,DC=cod1,DC=emi,DC=server,DC=com
LDAP_FILTER=
LDAP_UID=uid
LDAP_SCOPE=3
LDAP_TIMEOUT=5
DATABASE_TYPE=mysql
MYSQL_HOST=mysql
MYSQL_PORT=3306
MYSQL_USR=root
MYSQL_PWD=password
MYSQL_DATABASE=registry
REGISTRY_URL=http://registry:5000
TOKEN_SERVICE_URL=http://ui/service/token
EMAIL_HOST=smtp.mydomain.com
EMAIL_PORT=25
EMAIL_USR=sample_admin@mydomain.com
EMAIL_PWD=abc
EMAIL_SSL=false
EMAIL_FROM=admin <sample_admin@mydomain.com>
EMAIL_IDENTITY=
HARBOR_ADMIN_PASSWORD= adminpassword
PROJECT_CREATION_RESTRICTION=everyone
VERIFY_REMOTE_CERT=on
MAX_JOB_WORKERS=3
UI_SECRET=PYRqKqMa2TvvFzwR
JOBSERVICE_SECRET=N7MAOm4XtUq2clHj
TOKEN_EXPIRATION=30
CFG_EXPIRATION=5
GODEBUG=netdns=cgo
ADMIRAL_URL=NA
WITH_NOTARY=False
RESET=false


# /data/config/config.json

{
  "admin_initial_password": "\u003cenc-v1\u003exE08n8H1E5XY2woU051PYcumgx4ZVDCDgPI=",
  "admiral_url": "NA",
  "auth_mode": "ldap_auth",
  "cfg_expiration": 5,
  "database_type": "mysql",
  "email_from": "admin \u003csample_admin@mydomain.com\u003e",
  "email_host": "smtp.mydomain.com",
  "email_identity": "",
  "email_password": "\u003cenc-v1\u003e0CFNt/W0W2qb/xwApblxfPIQHg==",
  "email_port": 25,
  "email_ssl": false,
  "email_username": "sample_admin@mydomain.com",
  "ext_endpoint": "http://docker-registry.domain.com",
  "ldap_base_dn": "OU=Users,OU=JPCOREST,OU=COD,DC=cod1,DC=emi,DC=server,DC=com",
  "ldap_filter": "",
  "ldap_scope": 3,
  "ldap_search_dn": "",
  "ldap_search_password": "\u003cenc-v1\u003eHhN1KUilekDdo6Jn3Y5MSg==",
  "ldap_timeout": 5,
  "ldap_uid": "uid",
  "ldap_url": "ldap://myldap.server.com:389",
  "max_job_workers": 3,
  "mysql_database": "registry",
  "mysql_host": "mysql",
  "mysql_password": "\u003cenc-v1\u003enr6n+IqL2H3CtNNtVvKVlmYGfFJ80lLHT5s=",
  "mysql_port": 3306,
  "mysql_username": "root",
  "project_creation_restriction": "everyone",
  "registry_url": "http://registry:5000",
  "self_registration": false,
  "sqlite_file": "",
  "token_expiration": 30,
  "verify_remote_cert": true,
  "with_notary": false
}

**Comment by ywk253100** [comment] 2017-05-26 08:40
The ldap_search_dn in config.json is null, could you config it on web UI with the admin user and try it  again?

**Comment by biolounge** [comment] 2017-05-26 09:40
Can't login with admin credentials from web UI, getting invalid username and password error.

See the logs from ui.log file:

May 26 11:28:09 172.18.0.1 ui[17364]: 2017-05-26T09:28:09Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is db_auth
May 26 11:28:09 172.18.0.1 ui[17364]: 2017-05-26T09:28:09Z [DEBUG] [authenticator.go:71]: Login failed, locking admin, and sleep for 1.5s

**Comment by ywk253100** [comment] 2017-05-26 09:57
Edit the config.json file directly, fill in the ldap_search_dn and save it. After that retry the login with ldap user again.

BTW, how do you upgrade Harbor from 0.5 to 1.1.1? Seems that there is something wrong in you upgrading.

**Comment by biolounge** [comment] 2017-05-26 10:14
@ywk253100 I manually updated config.json by adding ldap_search_dn and retried the login with ldap user but still no change in situation.

For upgrading harbor from 0.5 to 1.1.1, I followed the instructions  in https://github.com/vmware/harbor/blob/master/docs/migration_guide.md  except steps 4,5 and 6.

**Comment by biolounge** [comment] 2017-05-29 09:49
@ywk253100 , I had to rollback to make it working again. Now I am running with Harbor 0.5.0.

**Comment by qingchn** [comment] 2017-06-01 06:08
I hava a same problem, is resolve？

**Comment by ywk253100** [comment] 2017-06-01 10:16
@qingchn We cannot reproduce the issue. Could you describe your case in detail? Did you upgrade from 0.5.0 to 1.1.1? Using LDAP? Can not login with admin and normal users? And please upload the harbor.cfg, /data/config/config.json, common/config/adminserver/env and all logs under directory /var/log/harbor?

**Comment by biolounge** [comment] 2017-06-07 09:39
Any updates on this issue?

@qingchn, could you provide details requested by @ywk253100

**Comment by biolounge** [comment] 2017-06-21 14:18
Is this issue resolved in Harbor 1.1.2?

**Comment by mattzuba** [comment] 2017-07-27 23:33
I'm using 1.1.2 with LDAP auth against AD and it's working fine for me.

**Comment by tibmeister** [comment] 2017-08-09 17:43
Running 1.1.2 and having nothing but issues.  Finally tracked it down to something that I never expected:
"system register user username failed, error: Error 1406: Data too long for column 'realname' at row 1"
My CN for my account is "Whitlock Jody (Admin)" and that's apparently now too long to use.  Under 0.5.0 and earlier this was not an issue.  Please realize that some folks may have a 40 char long Last Name, or 4 parts to their full CN (Other cultures).  This needs to be considered.

**Comment by reasonerjt** [comment] 2017-08-10 07:37
This is fixed in master will soon be released

**Comment by reasonerjt** [comment] 2017-11-07 04:50
Closing as the problems mentioned in this issue has all be fixed in 1.2 release.
Please open new issues if you see problems in authenticating LDAP user.

**Closed by reasonerjt** 2017-11-07 04:50 UTC
Labels: area/ldap, defer-candidate, kind/bug, kind/customer-found, priority/medium
