### ISSUE TITLE
[VIC] Can't download root cert

### ISSUE THREAD

**Issue by cuwab** [vmware/harbor#3527] opened 2017-11-02 04:01 UTC
I am trying to install vSphere Integrated Containers 1.2 from the OVA but once connected to my VIC appliance I can't download root cert from Administration > Configuration
Any idea?

![capture](https://user-images.githubusercontent.com/33305546/32309265-84a20920-bfde-11e7-9d4b-9de7b2e18985.PNG)

**Comment by reasonerjt** [comment] 2017-11-02 04:40
@cuwab in VIC the UI is bundled with another component,  there's a similar issue opened recently.
https://github.com/vmware/admiral/issues/215

I noticed the text looks incorrect in your screenshot, are you using a released .ova or a dev build?

**Comment by cuwab** [comment] 2017-11-02 05:29
Hi ! I use the latest released ova dowloaded from official vic website

**Comment by reasonerjt** [comment] 2017-11-02 06:42
so is it 1.2.1?

**Comment by eivanova** [comment] 2017-11-02 15:46
I could reproduce this issue with Chrome [Version 61.0.3163.100 (Official Build) (64-bit)], but not Firefox [53.0 (64-bit)]. I don't see anything special either in the console or in the requests.

P.S. While writing this I noticed that in my incognito window in Chrome the page has loaded okay.. Not sure what happened, but now it seems to be fine in all windows..

**Comment by andrewtchin** [comment] 2017-11-02 21:47
Also seen in https://github.com/vmware/vic-product/issues/821

**Comment by cuwab** [comment] 2017-11-02 23:07
Everything seems OK after reinstall VIC 1.1 and upgrade it to 1.2 so I can't check if there's failed http request, sorry :/

**Comment by steven-zou** [comment] 2017-11-08 05:32
@eivanova @andrewtchin,
  To locate the root cause of this issue, we need to confirm:
  Firstly, the current user has admin role;
  Secondly, the ca is in the right place.
  The above things have corresponding properties returned by the systeminfo api. When reproduced the issue, have you tried to check if the properties in the json data returned by the systeminfo are right? I'm wondering if there are some cache problems to interrupt the api to return the latest data.

**Comment by andrewtchin** [comment] 2017-11-08 18:54
I believe the user is admin and CA is generated and moved correctly by the VIC Appliance startup. @stuclem is the original reporter in vic-product #821

**Comment by steven-zou** [comment] 2017-11-22 07:23
Checked, it's already fixed in new .ova build. Close it.

**Closed by steven-zou** 2017-11-22 07:23 UTC
Labels: area/ui, kind/bug, priority/medium, target/vic-1.3
