### ISSUE TITLE
install.sh cannot detect docker-compose version properly

### ISSUE THREAD

**Issue by sflxn** [vmware/harbor#991] opened 2016-11-01 22:16 UTC
Install.sh in 0.4.5 does not detect docker-compose version properly.

```
loc@Devbox:~/Downloads/harbor$ docker --version
Docker version 1.12.3, build 6b644ec
loc@Devbox:~/Downloads/harbor$ docker-compose --version
docker-compose version 1.8.1, build 878cff1
loc@Devbox:~/Downloads/harbor$ sudo ./install.sh

[Step 0]: checking installation environment ...

Note: docker version: 1.12.3
✖ Need to install docker-compose(1.7.1+) by yourself first and run this script again.
loc@Devbox:~/Downloads/harbor$ 

```

docker-compose was installed via pip.

**Comment by yhua123** [comment] 2016-11-02 10:20
what's your OS?
I just tested this on UBUNTU14.04 and MacOS 10.11.2.

**Comment by lwh** [comment] 2016-11-08 15:22
I get this on CentOS 7
[Step 0]: checking installation environment ...
Note: docker version: 1.12.3
Need to install docker-compose(1.7.1+) by yourself first and run this script again.

**Comment by hainingzhang** [comment] 2016-11-10 03:36
@lwh  can you show detailed version of your OS and version of docker-compose?

**Comment by yhua123** [comment] 2016-11-11 03:43
@lwh 
On CentOS 7
#lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core
# ./install.sh 

[Step 0]: checking installation environment ...
Note: docker version: 1.11.0
Note: docker-compose version: 1.7.0

[Step 1]: preparing environment ...

**Comment by yhua123** [comment] 2016-11-16 07:20
Hi Lwh,
your problem resolved or not? we can't reproduce this issue. can you give us more information? thanks~

**Comment by yhua123** [comment] 2016-11-17 05:32
if this issue can't reproduce, i will close this in 24 hours.
if shown again, will reopen this issue again.

**Comment by lwh** [comment] 2016-11-18 15:12
I can't replicate it - I think it was a local problem with docker-compose. New builds I've tested don't run into the problem

**Closed** 2016-11-22 10:24 UTC
