### ISSUE TITLE
Broken Harbor/Admiral UI Data Loading

### ISSUE THREAD

**Issue by morris-jason** [vmware/harbor#3612] opened 2017-11-14 16:28 UTC
Data loading between tab redirects is broken in harbor build `harbor.v1.2.0-208-gfa83b3a` and admiral `884b0e757650`.

Steps to repro:
1) Go to https://sc-rdops-vm10-dhcp-59-141.eng.vmware.com:8282/ or https://10.161.115.45:8282/
2) Click on Admin Tab.
3) Click on Home Tab.
4) Click on Admin Tab again.
5) Go to configuration - you should see a generic config page, missing all of the config data like ova certs.
6) Go to projects, projects aren’t appearing either.
7) Click on Home tab, project doesn’t appear.

cc @wy65701436 @sergiosagu 
Please mark high priority. If this ends up not being a Harbor issue, let me know and I can open a new ticket in vmware/admiral.

**Comment by andrewtchin** [comment] 2017-11-14 16:29
![bugt](https://user-images.githubusercontent.com/1649165/32791449-aefc3244-c926-11e7-836f-27133b7c1e58.gif)

**Comment by wy65701436** [comment] 2017-11-14 16:37
I can reproduce it in Jason's env, but no error in the backend log.

**Comment by sergiosagu** [comment] 2017-11-14 17:25
I think that we have an issue in Jira about the Configuration tab that can be related (VBV-1724). @iilieva is investigating it and maybe she can add some more info.

**Comment by steven-zou** [comment] 2017-11-15 02:19
@morris-jason 
  Project management is provided by Admiral team. @sergiosagu has copied issue to their jira system.

@sergiosagu 
  Has Admiral upgraded the version of UI library Clarity?

**Comment by iilieva** [comment] 2017-11-15 14:04
@steven-zou We have not upgraded clarity libraries recently. Currently, we are using:
clarity-angular 0.9.9
clarity-icons" 0.9.9
clarity-ui 0.9.9

**Comment by steven-zou** [comment] 2017-11-22 07:22
It's not harbor issue. We'll close it.

**Closed by steven-zou** 2017-11-22 07:22 UTC
Labels: area/ui, kind/bug, priority/high, target/vic-1.3

**Comment by sergiosagu** [comment] 2017-11-22 07:56
It's fine to close it since it's working now, but the statement 
> It's not harbor issue.
doesn't seem completely accurate since it got fixed when Habor UI component in Admiral got updated to 0.5.11 :-)
