### ISSUE TITLE
Need 'Undo' action for recalling changes of configurations 

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#1757] opened 2017-03-23 10:16 UTC
Not only block leaving, but also need to provide 'Undo' or resetting actions to recall last changes.

**Comment by steven-zou** [comment] 2017-03-23 13:53
@wknet123 
Support resetting when you click 'Confirm'. What's the problem is?

**Comment by steven-zou** [comment] 2017-03-25 10:30
No design support. Mark this issue as 'Invalid' and close it.

**Closed by steven-zou** 2017-03-25 10:30 UTC
Labels: area/clarity-ui, invalid
