### ISSUE TITLE
How to dev or debug this project?

### ISSUE THREAD

**Issue by xwisen** [vmware/harbor#78] opened 2016-04-02 08:53 UTC
I have seen a docker-compose.yml in this project.But,it not a good way to debug.When I start deploy a development environment,I find it hard to me.The nginx is relay on harbor and there are so many env . So,how do you dev/debug this project?

**Comment by reasonerjt** [comment] 2016-04-02 08:58
Do you find any particular difficulty using docker-compose up?

**Comment by xwisen** [comment] 2016-04-02 09:08
I am a IDEA user.I do not want rebuild the Dockerfile every code changes.It to slow to me.Such as `go get -d github.com/docker/distribution`.So,I want to deploy the `harbor_msql`、`harbor_registry`、'harbor_nginx' alone.

**Comment by wknet123** [comment] 2016-04-02 15:39
In my opinion, you can start up Harbor project as to set registry and DB as base services of your dev environment, then edit the the UI config 'app.conf' file under the 'Deploy/config/ui' changing the http port number to another value that does not conflict to your current running up services, if you can't find this file, you may run up Harbor project properly first by using 'docker-compose up'. You now can run up another instance of UI at a different http port for developing or debugging.

**Comment by wknet123** [comment] 2016-04-02 16:11
As a supplement, you also need to export some environment variables with properly value set as below at least, before running up another UI instance. 
MYSQL_HOST= <ip_address>
MYSQL_PORT=3306
MYSQL_USR=root
MYSQL_PWD=root123
REGISTRY_URL=http://<ip_address>:5000
You may refer the full list at 'Deploy/config/ui/env'. Have fun!

**Comment by SEJeff** [comment] 2016-04-02 16:40
Duplicate of #31

**Comment by xwisen** [comment] 2016-04-03 03:50
@wknet123 Thinks for your answer.I will have a try.

**Closed** 2016-04-03 06:19 UTC
Labels: question

**Comment by xwisen** [comment] 2016-04-03 07:12
@wknet123 Maybe I should also change the '/nginx/nginx.conf' and '/nginx.https.conf' to suit upstream 'ui'.How do you debug this project?run 'docker-compose up' every code changes?or deploy other 
component without docker-compose?

**Comment by xwisen** [comment] 2016-04-03 07:13
@SEJeff Thanks for your remind[#31](https://github.com/vmware/harbor/issues/31).But,what I want is only rebuild the harbor project in every code changes because other step is a burden for me. Meanwhile,I want use 'docker-compose' due to it's convenience.
