### ISSUE TITLE
UI can't render switch pane for projects with project_id > 10

### ISSUE THREAD

**Issue by goredar** [vmware/harbor#853] opened 2016-09-29 11:38 UTC
UI's request for project list to 'api/projects?is_public=1&project_name=' returns part of actual list due to default pagination:
```
const (
	defaultPageSize int64 = 10
	maxPageSize     int64 = 100
)
```
UI can't find current project in that incomplete list and fails:
```
current language:English
visited:/repository
list project projectName: , isPublic:1
retrieve repositories, project_id:17
list repositories:17, q:
TypeError: Cannot read property 'project_id' of undefined
    at getProjectSuccess (harbor.app.min.js:15)
    at angular.min.js:95
    at angular.min.js:128
    at m.$eval (angular.min.js:142)
    at m.$digest (angular.min.js:140)
    at m.$apply (angular.min.js:143)
    at g (angular.min.js:95)
    at x (angular.min.js:100)
    at XMLHttpRequest.v.onload (angular.min.js:101)
loading-progress, toggleInProgress:undefined, hideTarget:true
Total Count:5, Page Size:15, Display Count:5, Page:1
loading-progress, toggleInProgress:false, hideTarget:true
```
Built from 0.4.0 tag.

**Comment by reasonerjt** [comment] 2016-09-29 15:32
@goredar I don't reproduce the error. could you also show the reponse of the api call?

**Comment by goredar** [comment] 2016-09-29 19:37
Reproduced on clean install after creating over 10 new projects.
```
curl 'http://localhost/api/projects?is_public=1&project_name='
[
  {
    "project_id": 10,
    "owner_id": 1,
    "name": "0001",
    "creation_time": "2016-09-29T19:21:18Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2016-09-29T19:21:18Z",
    "current_user_role_id": 0,
    "repo_count": 0
  },
  {
    "project_id": 2,
    "owner_id": 1,
    "name": "0002",
    "creation_time": "2016-09-29T19:20:00Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2016-09-29T19:20:00Z",
    "current_user_role_id": 0,
    "repo_count": 0
  },
  {
    "project_id": 3,
    "owner_id": 1,
    "name": "0003",
    "creation_time": "2016-09-29T19:20:08Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2016-09-29T19:20:08Z",
    "current_user_role_id": 0,
    "repo_count": 0
  },
  {
    "project_id": 4,
    "owner_id": 1,
    "name": "0004",
    "creation_time": "2016-09-29T19:20:17Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2016-09-29T19:20:17Z",
    "current_user_role_id": 0,
    "repo_count": 0
  },
  {
    "project_id": 5,
    "owner_id": 1,
    "name": "0005",
    "creation_time": "2016-09-29T19:20:24Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2016-09-29T19:20:24Z",
    "current_user_role_id": 0,
    "repo_count": 0
  },
  {
    "project_id": 6,
    "owner_id": 1,
    "name": "0006",
    "creation_time": "2016-09-29T19:20:29Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2016-09-29T19:20:29Z",
    "current_user_role_id": 0,
    "repo_count": 0
  },
  {
    "project_id": 7,
    "owner_id": 1,
    "name": "0007",
    "creation_time": "2016-09-29T19:20:33Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2016-09-29T19:20:33Z",
    "current_user_role_id": 0,
    "repo_count": 0
  },
  {
    "project_id": 11,
    "owner_id": 1,
    "name": "0008",
    "creation_time": "2016-09-29T19:21:23Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2016-09-29T19:21:23Z",
    "current_user_role_id": 0,
    "repo_count": 0
  },
  {
    "project_id": 8,
    "owner_id": 1,
    "name": "0009",
    "creation_time": "2016-09-29T19:20:43Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2016-09-29T19:20:43Z",
    "current_user_role_id": 0,
    "repo_count": 0
  },
  {
    "project_id": 9,
    "owner_id": 1,
    "name": "0010",
    "creation_time": "2016-09-29T19:21:00Z",
    "creation_time_str": "",
    "deleted": 0,
    "owner_name": "",
    "public": 1,
    "Togglable": false,
    "update_time": "2016-09-29T19:21:00Z",
    "current_user_role_id": 0,
    "repo_count": 0
  }
]
```

**Comment by wknet123** [comment] 2016-09-30 03:39
May be the bug of pagination in backend,  request page size is 15, but return 12 records. @ywk253100

**Comment by reasonerjt** [comment] 2016-09-30 04:54
Thanks, this is a issue in UI will fix it

**Comment by reasonerjt** [comment] 2016-09-30 06:58
There's a quick fix applied, however it introduces restriction that the drop down list will only show the projects in the same page as the current I'll open another issue to track it.

**Comment by goredar** [comment] 2016-09-30 07:10
Tanks a lot! However in my opinion API should not return parted result unless you explicitly request pagination.

**Comment by reasonerjt** [comment] 2016-09-30 07:12
Yes we'll revisit that, thanks for suggestion.

**Comment by bergtwvd** [comment] 2016-10-02 07:35
I have 11 projects in v0.40. Probably due to this same bug, I cannot modify the user membership of the 11th project. The options are just not shown.

**Comment by reasonerjt** [comment] 2016-10-10 04:06
I'm closing this issue as the fix is applied, we'll revisit the api and it will be tracked by #856 

@bergtwvd ,I created more than 10 projects and i didn't reproduce the issue you saw, I think it's not the same bug, if you are still seeing the issue please open a new issue.

**Closed by reasonerjt** 2016-10-10 04:06 UTC
Labels: bug

**Comment by bergtwvd** [comment] 2016-10-10 15:01
Did you test on v0.4.0?   I will open a bug for 0.4.0.
