### ISSUE TITLE
refresh page will lost delete menu option

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#2152] opened 2017-04-27 03:51 UTC
a normal user in repository's  tag page, refresh the page, the delete option disappeared
![iiiii](https://cloud.githubusercontent.com/assets/23101283/25467290/d52ff0ac-2b3f-11e7-83e4-c7f8fdc2e075.PNG)

**Comment by wknet123** [comment] 2017-04-27 04:07
This should be caused by members check deferring last route page, and the member data lost after reloading current page. I'll fix this issue by adding members check onto this route page.

**Comment by wknet123** [comment] 2017-04-27 04:15
Fixed with PR #2153

**Comment by reasonerjt** [comment] 2017-04-28 08:33
remove it from 1.1.1 since the effort to fix it is bigger than estimation.  @stuclem please add a release note, this is a known issue.  The work around is to click  "<Repositories" and click the link of repository from the list again, the "Delete" option will come back.

**Comment by stuclem** [comment] 2017-05-02 14:47
@reasonerjt I only just saw this. Belatedly added the issue to the release notes. Removing kind/note tag.

**Closed** 2017-05-03 13:53 UTC
Labels: area/clarity-ui, bug, target/1.1.1
