### ISSUE TITLE
[UI] Can't view clair log 

### ISSUE THREAD

**Issue by cbarzu** [vmware/harbor#3113] opened 2017-08-24 08:49 UTC
Hi, 

I have a little problem with the UI trying to view the log of a clair execution with version 1.2.0-rc2.
Steps to reproduce:
1. Go to any image. 
![image](https://user-images.githubusercontent.com/4789938/29657826-2db99454-88b9-11e7-9122-2c41f70b6468.png)

2. Scan the image

![image](https://user-images.githubusercontent.com/4789938/29658089-fe83e012-88b9-11e7-8144-fe7dd38beac6.png)

3. Click on `View Log`
![image](https://user-images.githubusercontent.com/4789938/29658122-1ae17d78-88ba-11e7-9041-6514065d076d.png)

And nothing happens. It should oppen a window seeing the error but nothing happens. In the developer console there isn't any error neither.

If I reload the page and go to the scanned image and click on View Log it works as expected.

Regards,
CLaudiu

**Comment by reasonerjt** [comment] 2017-08-24 09:11
looks like dup of #3050 
@cbarzu which build and which browser are you using?

**Comment by cbarzu** [comment] 2017-08-24 09:15
Firefox 54

**Comment by steven-zou** [comment] 2017-08-24 19:22
@pengpengshui 

  Please help to investigate this issue.

The root cause might be no scanning summary is retrieved instantly after the action is done.

`//Check error log
    viewLog(): void {
        if (this.summary && this.summary.job_id) {
            this.scanningJobLogViewer.open(this.summary.job_id);
        }
    }`

If no summary and job_id, no log window will be opened.

**Comment by ywk253100** [comment] 2017-08-25 07:37
I reproduced this issue, it only occurs when the image is scanned for the first time and nothing operations should not be done before the scanning is done.

**Comment by reasonerjt** [comment] 2017-08-30 09:21
Fixed in #3134

**Closed by reasonerjt** 2017-08-30 09:21 UTC
Labels: area/ui, kind/bug, priority/low, target/1.2.0
