### ISSUE TITLE
PKS/Harbor: Harbor services can not start after Harbor VM is rebooted

### ISSUE THREAD

**Issue by guillierf** [vmware/harbor#3942] opened 2018-01-06 00:18 UTC
CURRENTLY

have successfully deployed Harbor and used it with PKS:
images located on Harbor and successfully pulled by worker nodes when an app is deployed.

but when Harbor is rebooted from vCenter, it does not work anymore:
cannot push/pull images anymore from Harbor
Harbor web UI is inaccessible

STEPS TO REPRODUCE
1/ on vCenter, select the Harbor VM
2/ Reboot the VM

WORKAROUND
bosh restart Harbor VM:
$ bosh restart harbor-app/a68f47ef-9d2e-40d2-9f5d-623ff81a8e75 -d harbor-container-registry-cad62ba95951930b4a19

SOME LOGS:
after Harbor reboot, I got this constant output from Bosh:

$ bosh vms
Using environment '10.40.206.13' as client 'ops_manager'

Task 216. Done

Deployment 'harbor-container-registry-cad62ba95951930b4a19'

Instance                                         Process State  AZ       IPs           VM CID                                   VM Type  
harbor-app/a68f47ef-9d2e-40d2-9f5d-623ff81a8e75  starting       AZ-MGMT  10.40.206.15  vm-577c623d-b979-4a52-8647-8e3e71419f6c  large.disk  

1 vms

Task 217. Done

=> always in starting state. it never change to running state (observed for 30 min now)

**Comment by jessehu** [comment] 2018-01-07 11:22
Thanks Francis for reporting the issue. I confirm this is a bug, will fix it ASAP.
Here is a workaround : click 'Apply changes' on Ops Manager Dashboard which will bring all services back to normal.
cc @virtmerlin @steven-zou @reasonerjt , this is bug in Harbor Tile 1.3.0 release for PKS 0.8.

**Comment by steven-zou** [comment] 2018-01-07 14:23
@reasonerjt I remember harbor can be restarted after vm rebooting. Do we missing some configurations to make it loose the restartig capabilities?

**Comment by jessehu** [comment] 2018-01-07 14:38
I found the root cause in Harbor bosh release. All folders in /var/vcap/sys/run/ are deleted when Harbor VM is rebooted. The directory /var/vcap/sys/run/docker is created in prestart script of job docker, not in ctl script. After VM rebooted, only 'ctl start' is called, but not prestart script.

**Comment by jessehu** [comment] 2018-01-15 05:15
Fixed in Harbor Tile 1.3.1 release and trunk code. 
https://git.eng.vmware.com/harbor/habo/merge_requests/10

**Closed by jessehu** 2018-01-15 05:15 UTC
Labels: area/bosh-release, area/tile, found-in/pks-0.8, kind/bug, need-test-case, target/pks-1.0
