### ISSUE TITLE
Harbor's login page errors out with "SyntaxError: Unexpected end of JSON input" 

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2650] opened 2017-06-27 11:33 UTC
Build used : https://storage.googleapis.com/vic-product-ova-builds/vic-v1.1.1-11728-fe83551f.ova

![json-input-error](https://user-images.githubusercontent.com/25006749/27585308-59f93e58-5b59-11e7-95fd-ee3c6afc8941.PNG)

ui.log says:
Jun 27 11:21:58 172.18.0.1 ui[404]: 2017-06-27T11:21:58Z [ERROR] [base.go:79]: failed to get public projects: Get https://vic-st-h2-132.eng.vmware.com:8282/projects?%24filter=isPublic+eq+%27true%27: x509: certificate signed by unknown authority
Jun 27 11:21:58 172.18.0.1 ui[404]: 2017/06/27 11:21:58 #033[1;34m[router.go:829][D] | GET        | /api/statistics                          | 61.297621ms      | match      | /api/statistics 

creds: admin/Admin!23

[2017-06-27.zip](https://github.com/vmware/harbor/files/1105093/2017-06-27.zip)

**Comment by lgayatri** [comment] 2017-06-27 11:34
After login I see 
![image](https://user-images.githubusercontent.com/25006749/27585615-a03dd7ec-5b5a-11e7-91b0-6a009136d6e3.png)

**Comment by lgayatri** [comment] 2017-06-27 11:40
I am not able to create projects

![image](https://user-images.githubusercontent.com/25006749/27585876-7f269962-5b5b-11e7-9483-b93d793bcd45.png)

**Comment by reasonerjt** [comment] 2017-06-27 11:41
@wy65701436 is it a known issue?

**Comment by wy65701436** [comment] 2017-06-27 12:04
I will have an new build uploaded to GS, it's an old one.

**Comment by reasonerjt** [comment] 2017-06-27 17:16
@ywk253100 seems it's due to the self-signed cert?

**Comment by reasonerjt** [comment] 2017-06-27 17:29
@ywk253100 seems the root cause is we are using "with_admiral" flag to differentiate the PMS, but it's not enabled in Admiral's build, let's find a easy way to work around.

BTW another issue we need to look at, is the cert, please check with Sergio if PMS will be served by https, if it is, the PMS client need the CA.

**Comment by luguang** [comment] 2017-07-03 08:54
Any update on this?

**Comment by reasonerjt** [comment] 2017-07-04 13:24
This is due to dependency on security code, as for the cert issue @ywk253100 has a fix and we'll follow up to verify.  
@steven-zou Shall we disable the UI in integration mode?

**Comment by steven-zou** [comment] 2017-07-14 08:23
Work will be tracked by #2728

**Comment by reasonerjt** [comment] 2017-07-18 09:08
@lgayatri Please access Admiral's UI endpoint for integration test.

Closing the issue because Harbor's UI will be disabled in integration  mode.

**Closed by reasonerjt** 2017-07-18 09:08 UTC
Labels: kind/bug, priority/high
