### ISSUE TITLE
Error response from daemon: Head https://10.78.220.193/v2/: dial tcp 10.78.220.193:443: getsockopt: connection refused .  cannot use http(default use https) to connect a exist customer's http habor image base

### ISSUE THREAD

**Issue by frapposelli** [vmware/harbor#2273] opened 2017-05-10 03:40 UTC
@gonghuahill commented on [Thu May 04 2017](https://github.com/vmware/vic/issues/5017)

root@photon-Zzw3wkzzl [ /vic11 ]# docker pull 10.78.220.193/dcos/tomcat-8.0.39-jdk-1.7.0:201704291124
Error response from daemon: Head https://10.78.220.193/v2/: dial tcp 10.78.220.193:443: getsockopt: connection refused

4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.162"
May  4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.163"
May  4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.164"
May  4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.165"
May  4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.167"
May  4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.166"
May  4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.168"
May  4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.169"
May  4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.170"
May  4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.171"
May  4 2017 13:39:02.300Z INFO          "/test-dc04/host/cluster05/20.26.24.172"
May  4 2017 13:39:03.925Z INFO  License check OK on hosts:
May  4 2017 13:39:03.925Z INFO    "/test-dc04/host/cluster05/20.26.24.157"
May  4 2017 13:39:03.925Z INFO    "/test-dc04/host/cluster05/20.26.24.158"
May  4 2017 13:39:03.925Z INFO    "/test-dc04/host/cluster05/20.26.24.159"
May  4 2017 13:39:03.925Z INFO    "/test-dc04/host/cluster05/20.26.24.160"
May  4 2017 13:39:03.925Z INFO    "/test-dc04/host/cluster05/20.26.24.161"
May  4 2017 13:39:03.925Z INFO    "/test-dc04/host/cluster05/20.26.24.162"
May  4 2017 13:39:03.925Z INFO    "/test-dc04/host/cluster05/20.26.24.163"
May  4 2017 13:39:03.925Z INFO    "/test-dc04/host/cluster05/20.26.24.164"
May  4 2017 13:39:03.925Z INFO    "/test-dc04/host/cluster05/20.26.24.165"
May  4 2017 13:39:03.926Z INFO    "/test-dc04/host/cluster05/20.26.24.167"
May  4 2017 13:39:03.926Z INFO    "/test-dc04/host/cluster05/20.26.24.166"
May  4 2017 13:39:03.926Z INFO    "/test-dc04/host/cluster05/20.26.24.168"
May  4 2017 13:39:03.926Z INFO    "/test-dc04/host/cluster05/20.26.24.169"
May  4 2017 13:39:03.926Z INFO    "/test-dc04/host/cluster05/20.26.24.170"
May  4 2017 13:39:03.926Z INFO    "/test-dc04/host/cluster05/20.26.24.171"
May  4 2017 13:39:03.926Z INFO    "/test-dc04/host/cluster05/20.26.24.172"
May  4 2017 13:39:03.961Z INFO  DRS check OK on:
May  4 2017 13:39:03.961Z INFO    "/test-dc04/host/cluster05"
May  4 2017 13:39:04.394Z INFO
May  4 2017 13:39:05.522Z INFO  Creating virtual app "vch11_6"
May  4 2017 13:39:05.667Z INFO  Creating directory [cssds05_10] vch-vm
May  4 2017 13:39:05.678Z INFO  Datastore path is [cssds05_10] vch-vm
May  4 2017 13:39:05.678Z INFO  Creating appliance on target
May  4 2017 13:39:05.689Z INFO  Network role "client" is sharing NIC with "public"
May  4 2017 13:39:05.689Z INFO  Network role "management" is sharing NIC with "public"
May  4 2017 13:39:07.994Z INFO  Uploading images for container
May  4 2017 13:39:07.994Z INFO          "bootstrap.iso"
May  4 2017 13:39:07.995Z INFO          "appliance.iso"
May  4 2017 13:39:19.901Z INFO  Waiting for IP information
May  4 2017 13:39:35.047Z INFO  Waiting for major appliance components to launch
May  4 2017 13:39:35.188Z INFO  Obtained IP address for client interface: "20.26.24.106"
May  4 2017 13:39:35.188Z INFO  Checking VCH connectivity with vSphere target
May  4 2017 13:39:35.281Z INFO  vSphere API Test: https://20.26.24.254 vSphere API target responds as expected
May  4 2017 13:39:40.652Z INFO  Initialization of appliance successful
May  4 2017 13:39:40.652Z INFO
May  4 2017 13:39:40.652Z INFO  VCH Admin Portal:
May  4 2017 13:39:40.652Z INFO  https://20.26.24.106:2378
May  4 2017 13:39:40.652Z INFO
May  4 2017 13:39:40.652Z INFO  Published ports can be reached at:
May  4 2017 13:39:40.652Z INFO  20.26.24.106
May  4 2017 13:39:40.653Z INFO
May  4 2017 13:39:40.653Z INFO  Docker environment variables:
May  4 2017 13:39:40.653Z INFO  DOCKER_HOST=20.26.24.106:2375
May  4 2017 13:39:40.653Z INFO
May  4 2017 13:39:40.653Z INFO  Connect to docker:
May  4 2017 13:39:40.653Z INFO  docker -H 20.26.24.106:2375 info
May  4 2017 13:39:40.653Z INFO  Installer completed successfully
root@photon-Zzw3wkzzl [ /vic11 ]# export DOCKER_HOST=tcp://20.26.24.106:2375
root@photon-Zzw3wkzzl [ /vic11 ]# docker login http://10.78.220.193 -u admin -p *******
docker: "login" requires a maximum of 1 argument.
See 'docker login --help'.

Usage:  docker login [OPTIONS] [SERVER]

Log in to a Docker registry.
If no server is specified, the default is defined by the daemon.
root@photon-Zzw3wkzzl [ /vic11 ]# docker pull 10.78.220.193/dcos/tomcat-8.0.39-jdk-1.7.0:201704291124
Error response from daemon: Head https://10.78.220.193/v2/: dial tcp 10.78.220.193:443: getsockopt: connection refused
root@photon-Zzw3wkzzl [ /vic11 ]# ls
LICENSE        c_zj1.sh                                     vic-machine-darwin       vic-ui-linux
README         command.bat                                  vic-machine-linux        vic-ui-windows.exe
appliance.iso  harbor-offline-installer-0.5.0.tgz.filepart  vic-machine-windows.exe  vpxd.log
bootstrap.iso  sh                                           vic-machine.log          z_zj_in.sh
c_zj.sh        ui                                           vic-ui-darwin
root@photon-Zzw3wkzzl [ /vic11 ]# more c_zj1.sh
./vic-machine-linux create  --target 20.26.24.254 --force --image-store cssds05_10  --user administrator@vsphere.lo
cal --bridge-network dvPortGroup-bridge-c5   --compute-resource  cluster05 -p ******** --no-tls --public-network dv
PortGroup-ext-c5 --public-network-ip 20.26.24.106/24 --public-network-gateway 20.26.24.1  --management-network dvPo
rtGroup-ext-c5  --client-network dvPortGroup-ext-c5  --dns-server 20.26.24.100 -name vch11_6  -vs cssds05_10/vch-vm
:default --insecure-registry 0.0.0.0:0

---

@rogeliosanchez commented on [Thu May 04 2017](https://github.com/vmware/vic/issues/5017#issuecomment-299274921)

@gonghuahill , when you use docker login, have you tried using `docker login http://10.78.220.193` w/o the user and password?

---

@gonghuahill commented on [Fri May 05 2017](https://github.com/vmware/vic/issues/5017#issuecomment-299421703)

root@photon-Zzw3wkzzl [ /vic11 ]#  docker login 10.78.220.193:80
Username: admin
Password:
Error response from daemon: Head https://10.78.220.193:80/v2/: http: server gave HTTP response to HTTPS client

---

@gonghuahill commented on [Fri May 05 2017](https://github.com/vmware/vic/issues/5017#issuecomment-299424130)

I found the doc ,but use my docker command in a photon os , how can I config it ?
Pulling and pushing images using Docker client
 
NOTE: Harbor only supports Registry V2 API. You need to use Docker client 1.6.0 or higher.
 
Harbor supports HTTP by default and Docker client tries to connect to Harbor using HTTPS first, so if you encounter an error as below when you pull or push images, you need to add '--insecure-registry' option to  /etc/default/docker  (ubuntu) or  /etc/sysconfig/docker  (centos) and restart Docker:
 
 Error response from daemon: Get https://myregistrydomain.com/v1/users/: dial tcp myregistrydomain.com:443 getsockopt: connection refused. 
 
If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add
  --insecure-registry myregistrydomain.com  to the daemon's start up arguments.
 
In the case of HTTPS, if you have access to the registry's CA certificate, simply place the CA certificate at /etc/docker/certs.d/myregistrydomain.com/ca.crt .

---

@mdubya66 commented on [Fri May 05 2017](https://github.com/vmware/vic/issues/5017#issuecomment-299501529)

I use dvm to manage my docker clients.

https://howtowhale.github.io/dvm/

```
(mwilliamson) dubs:~ $ dvm ls
	1.11.2
	1.13.0
	17.04.0-ce
	17.05.0-ce-rc1
->	system (17.05.0-ce-rc1)
(mwilliamson) dubs:~ $ dvm --version
Docker Version Manager version 0.8.3 ()
(mwilliamson) dubs:~ $ dvm ls
	1.11.2
	1.13.0
	17.04.0-ce
	17.05.0-ce-rc1
->	system (17.05.0-ce-rc1)
(mwilliamson) dubs:~ $ dvm use 1.13.0
Now using Docker 1.13.0
(mwilliamson) dubs:~ $ dvm ls
	1.11.2
->	1.13.0
	17.04.0-ce
	17.05.0-ce-rc1
	system (17.05.0-ce-rc1)
(mwilliamson) dubs:~ $
```

---

@rogeliosanchez commented on [Fri May 05 2017](https://github.com/vmware/vic/issues/5017#issuecomment-299535809)

@frapposelli CC-ing for more info on http Harbor steps.

---

@frapposelli commented on [Mon May 08 2017](https://github.com/vmware/vic/issues/5017#issuecomment-299968135)

@gonghuahill are you trying to connect to a harbor instance deployed with the OVA?

---

@gonghuahill commented on [Tue May 09 2017](https://github.com/vmware/vic/issues/5017#issuecomment-300358361)

@frapposelli 
customer use  install.sh  install habour and habour in http mode.
![image](https://cloud.githubusercontent.com/assets/24300363/25881032/522fbea2-356d-11e7-914e-cb0ebca7d9f5.png)

![image](https://cloud.githubusercontent.com/assets/24300363/25881058/6d2de0ee-356d-11e7-8b73-976b0603180b.png)

root@photon-Zzw3wkzzl [ ~ ]# docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.1.0
 API version:  1.25
 Go version:   go1.8
 Git commit:   e974a51
 Built:        Fri Apr 14 19:53:17 2017
 OS/Arch:      linux/amd64
 Experimental: true

---

@gonghuahill commented on [Tue May 09 2017](https://github.com/vmware/vic/issues/5017#issuecomment-300359692)

@mdubya66 
update the create script ，and modifty docker.service ,and reboot the photon ,still the same error 
root@photon-Zzw3wkzzl [ /vic11 ]# more c_zj0508.sh
./vic-machine-linux create  --target 20.26.24.254 --force --image-store cssds05_
10  --user administrator@vsphere.local --bridge-network dvPortGroup-bridge-c5
--compute-resource  cluster05 -p ******* --no-tls --public-network dvPortGroup-
ext-c5 --public-network-ip 20.26.24.106/24 --public-network-gateway 20.26.24.1
--management-network dvPortGroup-ext-c5  --client-network dvPortGroup-ext-c5  --
dns-server 20.26.24.100 --insecure-registry 10.78.220.193:80   -name vch11_106
-vs cssds05_10/vch-vm:default

root@photon-Zzw3wkzzl [ /usr/lib/systemd/system ]# vi docker.service

[Unit]
Description=Docker Daemon
Documentation=http://docs.docker.com
Wants=network-online.target
After=network-online.target docker-containerd.service
Requires=docker-containerd.service

[Service]
Type=notify
EnvironmentFile=-/etc/default/docker
ExecStart=/usr/bin/docker daemon **--insecure-registery 10.78.220.193:80**  $DOCKER_OPTS \
          --containerd /run/containerd.sock
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-abnormal
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

---

@frapposelli commented on [Tue May 09 2017](https://github.com/vmware/vic/issues/5017#issuecomment-300364985)

@gonghuahill I see that the issue you're having is with the open source version of Harbor and not with the one bundled in the VIC OVA, I'm moving this issue to the appropriate repo.

**Comment by reasonerjt** [comment] 2017-05-10 05:06
@frapposelli @gonghuahill
**"--insecure-registery 10.78.220.193:80"**
There's typo in the parm.
Please use  **"--insecure-registry 10.78.220.193"**

**Comment by gonghuahill** [comment] 2017-05-10 08:19
@frapposelli @reasonerjt 
after move :80  I think the issue is pass. Thanks
　
root@photon-Zzw3wkzzl [ /vic11 ]# export DOCKER_HOST=20.26.24.107:2375
root@photon-Zzw3wkzzl [ /vic11 ]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@photon-Zzw3wkzzl [ /vic11 ]# docker pull 10.78.220.193/dcos/tomcat-8.0.39-jdk-1.7.0:201704291124
Pulling from dcos/tomcat-8.0.39-jdk-1.7.0
9bebe6ae2634: Pull complete
Digest: sha256:ac05c5f5c26e2fb6b2a1614655652a625718a1772052660fa575ba3edaa317fc
Status: Downloaded newer image for dcos/tomcat-8.0.39-jdk-1.7.0:201704291124

**Comment by reasonerjt** [comment] 2017-05-10 08:53
Thanks, closing.

**Closed by reasonerjt** 2017-05-10 08:53 UTC

**Comment by gonghuahill** [comment] 2017-05-11 03:42
when use docker run ? the same question happen  while pull is success ?

root@photon-Zzw3wkzzl [ /vic11 ]# docker pull 10.78.220.193/test/demo-test:201705111030
Pulling from test/demo-test
5eff8d6715f7: Pull complete
183ec01ed387: Pull complete
6a211bd806ef: Pull complete
Digest: sha256:7606898d5ed9b810ce03c13c28992cfbe3419c1b921ab5b416067d9681a15815

root@photon-Zzw3wkzzl [ /vic11 ]# docker run -p 8080:8080 -e JAVA_HOME=/app/jdk -d 10.70.220.193/test/demo-test:201705111030 sh /app/tomcat/bin/startup.sh
Unable to find image '10.70.220.193/test/demo-test:201705111030' locally
docker: Error response from daemon: Head https://10.70.220.193/v2/: dial tcp 10.70.220.193:443: getsockopt: connection timed out.
See 'docker run --help'.

**Comment by gonghuahill** [comment] 2017-05-12 00:26
@reasonerjt  please reopen the case

**Comment by gonghuahill** [comment] 2017-05-23 11:28
wrong ip address ahead10.70.220.193 , problem is solved ,thanks all .
