### ISSUE TITLE
ldap ddos

### ISSUE THREAD

**Issue by vitosans** [vmware/harbor#1480] opened 2017-02-27 23:02 UTC
When I use Harbor in LDAP mode, and I release a container via DCOS / Marathon and that container dies or is not able to launch for what ever reason and in DCOS / Marathon you have: 

"forcePullImage": true,

DCOS / Marathon / Docker will re-request the image from Harbor and you can ddos a LDAP server by consuming all file descriptors. Not sure why Harbor is asking LDAP for auth when this is a public repo so pull shouldn't need LDAP. 

```
ns-slapd   4888   fds   96u  IPv6 1819601       TCP our-ldap.somecompanyname-here.com:ldap->registry.somecompanyname-here.com:40608 (ESTABLISHED)
ns-slapd   4888   fds   97u  IPv6 1820053       TCP our-ldap.somecompanyname-here.com:ldap->registry.somecompanyname-here.com:40618 (ESTABLISHED)
ns-slapd   4888   fds   98u  IPv6 1820455       TCP our-ldap.somecompanyname-here.com:ldap->registry.somecompanyname-here.com:40628 (ESTABLISHED)
ns-slapd   4888   fds   99u  IPv6 1820907       TCP our-ldap.somecompanyname-here.com:ldap->registry.somecompanyname-here.com:40638 (ESTABLISHED)
ns-slapd   4888   fds  100u  IPv6 1821359       TCP our-ldap.somecompanyname-here.com:ldap->registry.somecompanyname-here.com:40648 (ESTABLISHED)
ns-slapd   4888   fds  101u  IPv6 1821812       TCP our-ldap.somecompanyname-here.com:ldap->registry.somecompanyname-here.com:40658 (ESTABLISHED)
ns-slapd   4888   fds  102u  IPv6 1822216       TCP our-ldap.somecompanyname-here.com:ldap->registry.somecompanyname-here.com:40668 (ESTABLISHED)
ns-slapd   4888   fds  103u  IPv6 1822676       TCP our-ldap.somecompanyname-here.com:ldap->registry.somecompanyname-here.com:40678 (ESTABLISHED)
ns-slapd   4888   fds  104u  IPv6 1823137       TCP our-ldap.somecompanyname-here.com:ldap->registry.somecompanyname-here.com:40688 (ESTABLISHED)
ns-slapd   4888   fds  105u  IPv6 1824486       TCP our-ldap.somecompanyname-here.com:ldap->registry.somecompanyname-here.com:40718 (ESTABLISHED)
```

Trimmed down.. once you hit the limits your ldap server can die.

**Comment by reasonerjt** [comment] 2017-02-28 10:20
It's because your Marathon tries to access docker image with credentials, and it will be redirected to token service with the credentials in basic auth header.
When Token Service sees the header it tries to verify the credentials.

Are you actually seeing a "too many open files" issue?

**Comment by vitosans** [comment] 2017-03-03 01:33
yes, I do see to many open files issue: 

```
[27/Feb/2017:15:03:47 -0800] - Listening on All Interfaces port 636 for LDAPS requests
[02/Mar/2017:16:45:33 -0800] - Not listening for new connections - too many fds open
[02/Mar/2017:16:45:34 -0800] - Listening for new connections again
[02/Mar/2017:16:45:34 -0800] - Not listening for new connections - too many fds open
[02/Mar/2017:16:45:34 -0800] - Listening for new connections again
[02/Mar/2017:16:45:34 -0800] - Not listening for new connections - too many fds open
[02/Mar/2017:16:45:34 -0800] - Listening for new connections again
[02/Mar/2017:16:45:35 -0800] - Not listening for new connections - too many fds open
[02/Mar/2017:16:45:35 -0800] - Listening for new connections again
[02/Mar/2017:16:45:38 -0800] - Not listening for new connections - too many fds open
[02/Mar/2017:17:02:00 -0800] - Listening for new connections again
[02/Mar/2017:17:02:00 -0800] - Not listening for new connections - too many fds open
[02/Mar/2017:17:20:06 -0800] - Listening for new connections again
[02/Mar/2017:17:20:06 -0800] - Not listening for new connections - too many fds open
[02/Mar/2017:17:22:02 -0800] - slapd shutting down - signaling operation threads
[02/Mar/2017:17:22:02 -0800] - slapd shutting down - closing down internal subsystems and plugins
```

I know I can crank up the FDS limit but that is only a way to extend the issue.

**Comment by vitosans** [comment] 2017-03-03 17:02
So I tried to remove the auth from mesos to limit this ddos - Even when images are pulled anonymous it still queries ldap - Also why is it keeping the socket open it should fail and close. I will see if I can look at the code and come up with a fix.

**Comment by reasonerjt** [comment] 2017-03-06 06:23
@vitosans thanks for the update.

we've refactored the code binding a user via ldap, it's on dev, I'll see if I can reproduce the issue without using marathon, if you can let us know the steps to reproduce the fd leaking issue it would be very helpful!

**Comment by reasonerjt** [comment] 2017-03-25 01:38
Will be an RC early Apr, hopefully the new release will be mid Apr.

**Comment by vitosans** [comment] 2017-03-31 17:24
@reasonerjt 

I moved it to Line 58 and built my own container and tested it today. It definitely helped but its still not 100% - Moving the defer ldap.Close() to 58 prevents getting multiples - but the root problem still persists. It looks to me that once harbor-ui contacts LDAP it never lets go over the connection 

```
ns-slapd  27620   fds   92u  IPv6 88911151       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54520 (ESTABLISHED)
ns-slapd  27620   fds   95u  IPv6 88911360       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54550 (ESTABLISHED)
ns-slapd  27620   fds   96u  IPv6 88911569       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54580 (ESTABLISHED)
ns-slapd  27620   fds   97u  IPv6 88911619       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54614 (ESTABLISHED)
ns-slapd  27620   fds   98u  IPv6 88911762       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54660 (ESTABLISHED)
ns-slapd  27620   fds   99u  IPv6 88911811       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54694 (ESTABLISHED)
ns-slapd  27620   fds  100u  IPv6 88912023       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54732 (ESTABLISHED)
ns-slapd  27620   fds  101u  IPv6 88912115       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54794 (ESTABLISHED)
ns-slapd  27620   fds  102u  IPv6 88912210       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54828 (ESTABLISHED)
ns-slapd  27620   fds  103u  IPv6 88912500       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54890 (ESTABLISHED)
ns-slapd  27620   fds  104u  IPv6 88912510       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54924 (ESTABLISHED)
ns-slapd  27620   fds  105u  IPv6 88912660       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54962 (ESTABLISHED)
ns-slapd  27620   fds  106u  IPv6 88912816       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:54992 (ESTABLISHED)
ns-slapd  27620   fds  107u  IPv6 88912918       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:55002 (ESTABLISHED)
ns-slapd  27620   fds  108u  IPv6 88913059       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:55012 (ESTABLISHED)
ns-slapd  27620   fds  109u  IPv6 88913085       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:55022 (ESTABLISHED)
ns-slapd  27620   fds  110u  IPv6 88913188       TCP ldaps-01.somecompany.com:ldaps->registry.somecompany.com:55048 (ESTABLISHED)
```

Hoping the refactoring fixes it once and for all.

**Comment by reasonerjt** [comment] 2017-04-13 05:57
Thanks we'll double check in latest code base.

**Comment by reasonerjt** [comment] 2017-04-21 11:14
I verified there's no such issue with latest code base, closing the issue, @vitosans please reopen if you still see the issue in your env.

**Closed by reasonerjt** 2017-04-21 11:14 UTC
Labels: 1.1.0-defer, bug, target/1.1.0.1
