### ISSUE TITLE
master分支go build报错，找不到go-sql-driver/mysql

### ISSUE THREAD

**Issue by yulingliu** [vmware/harbor#559] opened 2016-07-17 12:09 UTC
..\..\dao\base.go:26:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
		D:\Go_Workspace\src\github.com\vmware\harbor\vendor\github.com\go-sql-driver\mysql (vendor tree)
		D:\Go\src\github.com\go-sql-driver\mysql (from $GOROOT)
		D:\Go_Workspace\src\github.com\go-sql-driver\mysql (from $GOPATH)

**Comment by reasonerjt** [comment] 2016-07-18 03:40
This is expected, some dependent packages are not included in the repo per advice by our legal team.

If you want to run **go build** to build the code please refer to the Dockerfiles to install the required packages via **go get**

**Comment by xiaods** [comment] 2016-07-23 00:01
@reasonerjt i suggest use gvt and dockerfile to track go package. it will let the environment is independent.

**Comment by reasonerjt** [comment] 2016-07-23 09:04
@xiaods thanks for suggestion, we use govendor for vendor package management, but the issue is we can not include the source file of some vendor packages in the repo, so go build fails.  Maybe we can put the reference in meta file such as vendor.json but ignore them so the packages won't be pushed to repo.

**Comment by xiaods** [comment] 2016-07-25 10:59
@reasonerjt yeah, it tips.

**Comment by xiaods** [comment] 2016-07-25 10:59
gvt is prefer tool

**Comment by hainingzhang** [comment] 2016-09-13 03:59
not an issue.   Closing it for now. Please reopen if needed.

**Closed by hainingzhang** 2016-09-13 03:59 UTC
