### ISSUE TITLE
'Remove' in Action is not clickable.

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#5253] opened 2018-07-05 06:10 UTC
![image](https://user-images.githubusercontent.com/2841473/42305334-18becf96-805d-11e8-8664-d4c063b3734f.png)

**Comment by reasonerjt** [comment] 2018-07-17 09:39
Due to issue in Clarity will find a workaround.

**Comment by zhoumeina** [comment] 2018-07-27 07:48
clr-datagrid {
    ::ng-deep clr-checkbox {
        position: inherit;
    }
}
in the production environment not working.

**Comment by zhoumeina** [comment] 2018-07-30 02:36
This is not a clarity issue. The root cause is the process of production environment packaging. This error only happended in production environment. We should refactor the production enrironment package process to make it the same as development environment. This work should be started after 1.6 release.

**Comment by zhoumeina** [comment] 2018-08-02 10:31
comment error fixed by #5483

**Closed by zhoumeina** 2018-08-02 10:31 UTC
Labels: area/ui, kind/automation-found, kind/bug, target/1.7
