### ISSUE TITLE
Certificate issue with Harbor and docker daemon

### ISSUE THREAD

**Issue by sflxn** [vmware/harbor#1063] opened 2016-11-11 00:03 UTC
The standard way to create certificates for static IP and FQDN for Harbor works fine, but it does not work with standard docker daemon.

1) Creating certificate for static IP works fine for Harbor if you're browsing it.  However, standard docker daemon cannot connect to it.
```
Error response from daemon: Get https://10.143.2.229/v1/users/: x509: certificate signed by unknown authority
```

2) Creating a certificate for FQDN works fine for Harbor, but standard docker daemon cannot connect to it unless you also include subjectAltName.  This is not common.  Most instructions including those on docker's website or the Harbor instruction website say to create certificate for FQDN OR static IP.

I have a feeling the problem is the script updating the nginx conf file.

**Comment by sflxn** [comment] 2016-11-11 00:11
This is going to be a problem if users are using a load balancer.

**Comment by reasonerjt** [comment] 2016-11-11 06:58
@sflxn if you want to use docker to access Harbor using IP, then the IP has to be in IPSAN of the cert of Harbor.

if you are using FQDN to access Harbor, putting the FQDN in CN of the cert should work.

**Comment by ywk253100** [comment] 2016-11-11 07:02
For 1, this is the expected behaviour. If your certificate is signed by unknown authority, you should either put the certificate of CA under directory /etc/docker/certs.d/IP_or_FQDN/ or add --insecure-registry to docker daemon.
For 2, if you use Harbor under version 0.4.5(included), no matter IP or FQDN is used to create certificate, you should include IP as the subjectAltName. In next release, subjectAltName is not needed anymore if use FQDN.

**Comment by reasonerjt** [comment] 2016-11-11 07:21
@sflxn, there are several issues involved.
When you setup Harbor with HTTPS and tries to use docker to access it, you may see 2 kinds of errors.

1) If you use a self-signed cert, docker may complain the cert is signed by unknown authority, this can be fixed by putting the CA cert into /etc/xxxx directory as described in previous comment.

2) docker may complain mismatch of IP or FQDN between the one you used and what is set in the cert.  Now, regarding setting the cert, for FQDN it should be in the CN of the cert for IP, it should be in the IPSAN of the cert.  However, now if you install via .ova, our installation script will always try to setup Harbor using IP, so when you use FQDN to access Harbor, even when the Harbor is using a cert with FQDN in the CN you may still see error, this issue is tracked by #995 and will be fixed within next couple of days.

Hope this helps, any further issues please add commet.

**Comment by sflxn** [comment] 2016-11-11 18:14
Yes, I am aware that we must add the CA cert in /etc/docker/certs.d/IPorFQDN.  This only works if the server certificate has both FQDN and subjectAltName.  If the certificate was created with static IP instead of FQDN, it does not work.  If we're creating a certificate, we should not have to use --insecure-registry.  That defeats the exercise of generating a certificate.

**Comment by reasonerjt** [comment] 2016-11-14 11:22
@sflxn I believe static IP works, as long as the CA cert is put into  /etc/docker/certs.d/IP.

As for this particular error in OP:
```
Error response from daemon: Get https://10.143.2.229/v1/users/: x509: certificate signed by unknown authority
```
I believe it's due to the CA cert is not placed correctly.

**Comment by sflxn** [comment] 2016-11-14 18:07
@reasonerjt Have you tested static IP in /etc/docker/certs.d/IP?  I spent over a day trying it.  If I can't get it to work, I suspect customers will also have trouble.  If you guys get around to verifying it works, please let me know and provide the instructions.  Is this part of your tests?

**Comment by sflxn** [comment] 2016-11-14 22:34
@reasonerjt I figured out why static ip is not working.  You guys have another bug.  When creating the certificates, common name must be set to the static ip address.  Your instructions do not say to do this.  Like nearly ALL certificate generation instructions, your's say to either put in FQDN or your name.  I believe there is an error in your startup script.

One other thing, nearly every VMware dev outside of the Harbor team is having problems with the instructions your docs provide.  You guys really need to test your docs.  All of the issues I found were bugs.  Since Harbor is going out with VIC Engine as one product, we must make sure that customers do not have any issues if following the instructions.  If internal VMware engineers are having difficulty, it's guaranteed our customers will have it worst.

**Comment by reasonerjt** [comment] 2016-11-15 12:29
@sflxn  sorry for the extra effort.
However, like I saind

> When creating the certificates, common name must be set to the static ip address.

This is incorrect.

I just verified by creating a certificate, server.crt. If I type this command:
```
openssl x509 -in ./server.crt -noout -text
```
I can see this in the output:
```
 Subject: C=AU, ST=Some-State, O=Internet Widgits Pty Ltd, CN=**not-staticIP**
```
So you see the static IP is **not** in the common name, what matters is the following chunk:
```
X509v3 extensions:
            X509v3 Subject Alternative Name:
                IP Address:10.117.4.174
```
And I can successfully docker login to 10.117.4.174 via docker login, using https.  And there's instructions in our doc to put IP in the x509v3 SAN:

> If you're using IP, say 192.168.1.101 to connect your registry host, you may instead run the command below:

>  echo subjectAltName = IP:192.168.1.101 > extfile.cnf
> 
>   openssl ca -in yourdomain.com.csr -out yourdomain.com.crt -cert ca.crt -keyfile ca.key -extfile extfile.cnf -outdir .
> 

The process to use openssl to generate cert for registry is tricky, but we have tested to follow the instructions in the doc to create cert and verify things work.  And by the way, I'm peronally a little reluctant to show this doc to customer as IMO the steps to generate a self-signed cert falls out of the scope of this project, customer may generate a cert not following the steps in our doc.

I agree the doc needs improvement, we're going through the doc to make sure things work, and the widgets of .ova has some limitations, which make the importing process a bit confusing.  If you see any problems please don't hesitate to communicate with us or open issues here, we'll follow up and fix it.

**Comment by reasonerjt** [comment] 2016-11-24 07:59
closing the issue as we've verified the https doc, and for .ova deployment Harbor will generate a self-signed cert by default.

@sflxn please reopen it if you think there's further issues need to be fixed.

**Closed by reasonerjt** 2016-11-24 07:59 UTC
