### ISSUE TITLE
Each Harbor will delete image again and again when you delete an image in the project which has a policy of replication from each other between two harbor.

### ISSUE THREAD

**Issue by gdonzy** [vmware/harbor#1250] opened 2016-12-15 05:32 UTC
1)Version of docker engine and docker-compose

**Version of docker engine:**
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        
 OS/Arch:      linux/amd64

**docker-compose version**
docker-compose version 1.8.1, build 878cff1

2)Config files of harbor, you can get them by packaging "Deploy/config" directory
[1.18.config.zip](https://github.com/vmware/harbor/files/653842/1.18.config.zip)
[1.21.config.zip](https://github.com/vmware/harbor/files/653843/1.21.config.zip)

3)Log files, you can get them by package the /var/log/harbor/ 
[1.18.log.zip](https://github.com/vmware/harbor/files/653845/1.18.log.zip)
[1.21.log.zip](https://github.com/vmware/harbor/files/653846/1.21.log.zip)

steps:
1. config policy of replication from each other between  two harbor
2. docker push an image into the project
3. delete the image
harbor will delete the image again and again.

**Comment by reasonerjt** [comment] 2016-12-15 05:33
dup?
@ywk253100

**Comment by gdonzy** [comment] 2016-12-15 05:39
duplicate from each other.Maybe every node will send a sinal to another after deleted, so it can't stop.

**Comment by ywk253100** [comment] 2016-12-15 05:51
@gdonzy Thank you for reporting this. It's a duplicate of #1222 and has been fixed.

**Closed** 2016-12-16 03:15 UTC
