### ISSUE TITLE
all LDAP users being logged in as "admin" in WebUI, 1.1.0

### ISSUE THREAD

**Issue by jaychris** [vmware/harbor#2109] opened 2017-04-21 17:52 UTC
Using the "ldap_auth" backend, any LDAP user that authenticates gets logged in as the built in "admin" account.

Successful auth for LDAP user:
```
Apr 21 17:47:34 172.18.0.1 ui[6016]: 2017-04-21T17:47:34Z [DEBUG] [authenticator.go:59]: Current AUTH_MODE is ldap_auth
Apr 21 17:47:34 172.18.0.1 ui[6016]: 2017-04-21T17:47:34Z [DEBUG] [ldap.go:145]: one or more ldapFilter: (&(objectClass=*)(sAMAccountName=build))
Apr 21 17:47:34 172.18.0.1 ui[6016]: 2017/04/21 17:47:34 #033[1;34m[router.go:829][D] | POST       | /login                                   | 62.183293ms      | match      | /login                                   | #033[0m

```

After authentication, the DEBUG messages in ui.log show this:
```
Apr 21 17:47:49 172.18.0.1 ui[6016]: 2017-04-21T17:47:49Z [DEBUG] [base.go:132]: No valid user id in session.
```

and then:
```
Apr 21 17:47:49 172.18.0.1 ui[6016]: 2017-04-21T17:47:49Z [DEBUG] [authutils.go:87]: user: admin, access: &{repository  test/delete [push * pull]}
```

**Comment by jaychris** [comment] 2017-04-21 18:23
perhaps this is related to [#2034](https://github.com/vmware/harbor/issues/2034), and the lack of an allowance for sAMAccountName.  I notice all my LDAP (AD) users are showing up after logging in with no usernames listed

**Comment by sgallerand** [comment] 2017-04-21 20:56
Hello,

Same issue and any valid user in my ldap scope gets loggued , even with a bad password.

**Comment by ywk253100** [comment] 2017-04-24 02:22
@jaychris It should be caused by #2034 , and we will have a fix for this.

**Comment by reasonerjt** [comment] 2017-04-27 05:40
Closing this issue and tracking by #2034

**Closed by reasonerjt** 2017-04-27 05:40 UTC
Labels: need-test-case, target/1.1.1
