### ISSUE TITLE
After 5+ days of uptime, Harbor login page reports "We are unable to perform your action because internal server errors have occurred

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2387] opened 2017-05-26 08:41 UTC
Harbor login page  reports "We are unable to perform your action because internal server errors have occurred" after 5+ days of uptime.
![internalservererror](https://cloud.githubusercontent.com/assets/25006749/26487092/9ef2a848-421b-11e7-8ab8-a496c50314a6.PNG)
"
Please see the attached screenshot.

/var/log/harbor/2017-05-26/proxy.log says:

May 26 08:36:25 172.18.0.1 proxy[386]: 10.146.13.86 - "GET /api/repositories/top?detail=1 HTTP/1.1" 500 21 "https://10.197.37.132/harbor/sign-in" "Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36" 0.048 0.048 .
May 26 08:36:50 172.18.0.1 proxy[386]: 10.146.13.86 - "GET /api/repositories/top?detail=1 HTTP/1.1" 500 21 "https://10.197.37.132/harbor/sign-in" "Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36" 0.045 0.045 .

vm-support attached
[vm-2017-05-26.12069.tar.gz](https://github.com/vmware/harbor/files/1031282/vm-2017-05-26.12069.tar.gz)
.

**Comment by ywk253100** [comment] 2017-05-26 08:47
Please provide the logs under directory /var/log/harbor/.

**Comment by lgayatri** [comment] 2017-05-26 08:56
uploaded all logs under /var/log/harbor [harbor.tar.gz](https://github.com/vmware/harbor/files/1031322/harbor.tar.gz)

**Comment by ywk253100** [comment] 2017-05-26 09:02
According to the logs "token signed by untrusted key with ID: \"WFE3:RDVI:F6KL:GF4Q:CM32:4NHJ:E7FI:IVZL:L5RJ:S23L:BJDU:X7TK\", the key used to encrypt and decrypt token does not match, restart Harbor by running docker-compose down and docker-compose up -d should resolve the issue.

**Comment by lgayatri** [comment] 2017-05-26 09:15
Can you please let me know how this key got changed? Thanks for the workaround but as part of uptime, we do not expect any such discrepancy.

**Comment by lgayatri** [comment] 2017-05-26 09:17
Filed https://github.com/vmware/vic/issues/5265 for harbor logs missing from support bundle

**Comment by ywk253100** [comment] 2017-05-26 09:26
Did you regenerate the key by running prepare or install.sh and restart some containers of Harbor instead all of them?

**Comment by lgayatri** [comment] 2017-05-26 09:31
This Harbor is running of the integrated OVA and was not restarted.
I did not regenerate any key but was using the harbor instance as it comes by default with OVA.

**Comment by hainingzhang** [comment] 2017-05-28 03:28
There was an issue when the OVA was rebooted without properly shutting down (such as power loss, or press reboot button of VM on vCenter )   @lgayatri 

@wy65701436 Have we found the reason for the reboot yet?

**Comment by lgayatri** [comment] 2017-05-29 05:55
@hainingzhang 
I checked the vmware.log of this VM and here is the snippet that 10 days ago from now, there was a reboot on this OVA.
[root@w2-hs2-d2616:/vmfs/volumes/58f7256a-fc3c1570-7bdb-0cc47a59dc5c/vic-v1.1.1-rc2-1f1711a0.ova] cat *.log | grep -i "CPU reset: soft"
...
2017-05-18T06:55:31.396Z| vcpu-1| I125: CPU reset: soft (mode 0)
2017-05-18T06:55:32.348Z| vcpu-1| I125: CPU reset: soft (mode 0)
[root@w2-hs2-d2616:/vmfs/volumes/58f7256a-fc3c1570-7bdb-0cc47a59dc5c/vic-v1.1.1-rc2-1f1711a0.ova] cat *.log | grep -i "CPU reset: hard"
...
2017-05-18T06:55:30.366Z| vcpu-0| I125: CPU reset: hard (mode 0)

Current uptime:
 5:57:51 up 10 days, 23:11:54, load average: 0.89, 0.89, 0.89
date
Mon May 29 05:58:03 UTC 2017

**Comment by luguang** [comment] 2017-05-31 02:16
It looks risky for me if we can't find the reasonable root cause of that reboot.

**Comment by ywk253100** [comment] 2017-05-31 02:55
We are trying to reproduce the issue.

**Comment by wy65701436** [comment] 2017-05-31 04:06
The root cause is that, reset machine will not raise an stop/shutdown signal to systemd service(harbor.service), thus all the running containers will not be stop and rm. 
At the next start phase(OVA), docker will start these containers automatically. At the same time, the systemd service is running prepare.sh and starting Harbor.

This causes some of the containers are consuming the old key, and others are consuming the newly generated key by prepare.sh.

OVA has to control the life cycle of all these containers. The start script should know if all the containers are starting by docker, if so, here needs to add one more step to force shutdown Harbor. And this could fix the problem.

**Comment by wy65701436** [comment] 2017-05-31 06:08
Add @frapposelli

**Comment by frapposelli** [comment] 2017-05-31 08:18
this is a dup of https://github.com/vmware/vic/issues/5035

see my comment for a workaround https://github.com/vmware/vic/issues/5035#issuecomment-299515083

**Comment by reasonerjt** [comment] 2017-07-18 09:29
OK closing.

**Closed by reasonerjt** 2017-07-18 09:29 UTC
