### ISSUE TITLE
the service is not stable

### ISSUE THREAD

**Issue by milliant** [vmware/harbor#99] opened 2016-04-13 00:55 UTC
At the very beginning ,I have logined the private registry,but failed to push a images to regitry.And then ,a few minutes later,I try again,and I pushed successfully.So that's happening?
![problems](https://cloud.githubusercontent.com/assets/6259839/14479778/a05b981a-0154-11e6-8a95-636e93e1dcff.png)

**Comment by tuxknight** [comment] 2016-04-13 02:17
Which release version did you use ?

**Comment by milliant** [comment] 2016-04-13 02:27
how to get to know the version.I start harbor from source code.

**Comment by reasonerjt** [comment] 2016-04-13 03:02
@milliant @tuxknight this seems a known issue and probably has been fixed in latest code.

If you use "git clone" to get the source you can let me know the latest id via "git log"

**Comment by tuxknight** [comment] 2016-04-13 05:46
I notice that the latest release had refactored database.

Is there any guide about migration between versions ?

**Comment by reasonerjt** [comment] 2016-04-13 06:21
@tuxknight we are working on a migrate script for data migration, but currently user will have to re create the DB.

btw, as this is another topic,  please be kindly suggested to open a new issue next time...

**Comment by reasonerjt** [comment] 2016-04-18 09:30
@milliant any update on this issue? Did you have a chance to try with latest code?

**Comment by milliant** [comment] 2016-04-25 12:33
sorry ,My reply is too late。
After I update to the latest source code,the problem doesn't appear any more. But I meet a new problem:
![harbor question 2](https://cloud.githubusercontent.com/assets/6259839/14783760/6dd58f16-0b24-11e6-8892-4986a63e89d9.png)
![harbor q2](https://cloud.githubusercontent.com/assets/6259839/14783810/adf0bdbe-0b24-11e6-9a01-6840e97b1313.png)

when I push a images to Harbor, it stopped without completed and a error appears on web ui..

**Comment by reasonerjt** [comment] 2016-04-26 12:00
looks like an issue in registry, did you check the log?
and is it reproducible?

**Closed** 2016-05-19 10:41 UTC
