### ISSUE TITLE
Images and replication endpoints/rules not appearing in UI after upgrade from 1.1.1 to 1.2

### ISSUE THREAD

**Issue by stuclem** [vmware/harbor#3163] opened 2017-09-06 10:41 UTC
Per https://github.com/vmware/admiral/issues/193, images are not appearing in the unified VIC UI after upgrading from 1.1.1 to 1.2. @reasonerjt suggests that this is not related to the change of IP address, as I suspected in https://github.com/vmware/admiral/issues/193. I tested upgrade again by setting the same IP address on the 1.2 appliance, and images still did not show up.

**Comment by reasonerjt** [comment] 2017-09-06 10:43
The root cause is that the project ID will be changed after migrating to Admiral, and Harbor does not reflect the change in its own DB for old data.

**Comment by stuclem** [comment] 2017-09-06 10:47
Replication endpoints and rules also do not show up after the upgrade. I assumed that this was to be expected, but @reasonerjt tells me that they should migrate.

**Comment by wy65701436** [comment] 2017-09-08 06:37
Passed on latest OVA RC3 build, close it.

**Closed by wy65701436** 2017-09-08 06:37 UTC
Labels: kind/impact-ova, priority/high, product/vic, target/1.2.0
