### ISSUE TITLE
can acess the ui ,but can't login. 

### ISSUE THREAD

**Issue by chowyu08** [vmware/harbor#593] opened 2016-07-27 07:17 UTC
1)Version of docker engine and docker-compose
![image](https://cloud.githubusercontent.com/assets/16483518/17166847/158bddac-540c-11e6-97d2-604640a929eb.png)
![image](https://cloud.githubusercontent.com/assets/16483518/17166873/2aed3bdc-540c-11e6-88d1-4b4d5a012f9e.png)

2)Config files of harbor, you can get them by packaging "Deploy/config" directory
![image](https://cloud.githubusercontent.com/assets/16483518/17166882/46ac8918-540c-11e6-9265-e38eda8180c3.png)

question: 
I can acess the ui 
![image](https://cloud.githubusercontent.com/assets/16483518/17166993/f3d6be60-540c-11e6-82e2-3af78a2943e8.png)

but when I login in 
![image](https://cloud.githubusercontent.com/assets/16483518/17167007/140c1a5e-540d-11e6-9303-aa10e775a8b6.png)

why?

**Comment by chowyu08** [comment] 2016-07-27 07:37
docker_registry.log

Jul 27 13:21:57 cloud2 docker/registry[4145]: time="2016-07-27T05:21:57.196244234Z" level=info msg="debug server listening localhost:5001" 
Jul 27 13:21:57 cloud2 docker/registry[4145]: time="2016-07-27T05:21:57.198202863Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=500ms, headers=map[]" go.version=go1.6.1 instance.id=7fb2fddf-50b0-463f-a92a-b90c8fda364e service=registry version=v2.4.0 
Jul 27 13:21:57 cloud2 docker/registry[4145]: time="2016-07-27T05:21:57.198319777Z" level=info msg="redis not configured" go.version=go1.6.1 instance.id=7fb2fddf-50b0-463f-a92a-b90c8fda364e service=registry version=v2.4.0 
Jul 27 13:21:57 cloud2 docker/registry[4145]: time="2016-07-27T05:21:57.238094947Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.1 instance.id=7fb2fddf-50b0-463f-a92a-b90c8fda364e service=registry version=v2.4.0 
Jul 27 13:21:57 cloud2 docker/registry[4145]: time="2016-07-27T05:21:57.23846769Z" level=debug msg="configured \"token\" access controller" go.version=go1.6.1 instance.id=7fb2fddf-50b0-463f-a92a-b90c8fda364e service=registry version=v2.4.0 
Jul 27 13:21:57 cloud2 docker/registry[4145]: time="2016-07-27T05:21:57.238576433Z" level=info msg="listening on [::]:5000" go.version=go1.6.1 instance.id=7fb2fddf-50b0-463f-a92a-b90c8fda364e service=registry version=v2.4.0 
Jul 27 13:25:29 cloud2 docker/registry[4145]: time="2016-07-27T05:25:29.023838307Z" level=info msg="debug server listening localhost:5001" 
Jul 27 13:25:29 cloud2 docker/registry[4145]: time="2016-07-27T05:25:29.025080155Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=500ms, headers=map[]" go.version=go1.6.1 instance.id=ee0ee84c-d2e8-4d8b-9dbd-e98eb9e16903 service=registry version=v2.4.0 
Jul 27 13:25:29 cloud2 docker/registry[4145]: time="2016-07-27T05:25:29.025421679Z" level=info msg="redis not configured" go.version=go1.6.1 instance.id=ee0ee84c-d2e8-4d8b-9dbd-e98eb9e16903 service=registry version=v2.4.0 
Jul 27 13:25:29 cloud2 docker/registry[4145]: time="2016-07-27T05:25:29.052384325Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.1 instance.id=ee0ee84c-d2e8-4d8b-9dbd-e98eb9e16903 service=registry version=v2.4.0 
Jul 27 13:25:29 cloud2 docker/registry[4145]: time="2016-07-27T05:25:29.052646928Z" level=debug msg="configured \"token\" access controller" go.version=go1.6.1 instance.id=ee0ee84c-d2e8-4d8b-9dbd-e98eb9e16903 service=registry version=v2.4.0 
Jul 27 13:25:29 cloud2 docker/registry[4145]: time="2016-07-27T05:25:29.052708738Z" level=info msg="listening on [::]:5000" go.version=go1.6.1 instance.id=ee0ee84c-d2e8-4d8b-9dbd-e98eb9e16903 service=registry version=v2.4.0 
Jul 27 13:26:21 cloud2 docker/registry[4145]: time="2016-07-27T05:26:21.106557626Z" level=info msg="debug server listening localhost:5001" 
Jul 27 13:26:21 cloud2 docker/registry[4145]: time="2016-07-27T05:26:21.107853461Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=500ms, headers=map[]" go.version=go1.6.1 instance.id=34c949b0-8279-45bd-8fc4-db2fa3a108e0 service=registry version=v2.4.0 
Jul 27 13:26:21 cloud2 docker/registry[4145]: time="2016-07-27T05:26:21.107935176Z" level=info msg="redis not configured" go.version=go1.6.1 instance.id=34c949b0-8279-45bd-8fc4-db2fa3a108e0 service=registry version=v2.4.0 
Jul 27 13:26:21 cloud2 docker/registry[4145]: time="2016-07-27T05:26:21.137595302Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.1 instance.id=34c949b0-8279-45bd-8fc4-db2fa3a108e0 service=registry version=v2.4.0 
Jul 27 13:26:21 cloud2 docker/registry[4145]: time="2016-07-27T05:26:21.137879975Z" level=debug msg="configured \"token\" access controller" go.version=go1.6.1 instance.id=34c949b0-8279-45bd-8fc4-db2fa3a108e0 service=registry version=v2.4.0 
Jul 27 13:26:21 cloud2 docker/registry[4145]: time="2016-07-27T05:26:21.137946883Z" level=info msg="listening on [::]:5000" go.version=go1.6.1 instance.id=34c949b0-8279-45bd-8fc4-db2fa3a108e0 service=registry version=v2.4.0 
Jul 27 13:34:52 cloud2 docker/registry[4145]: time="2016-07-27T05:34:52.217534531Z" level=info msg="debug server listening localhost:5001" 
Jul 27 13:34:52 cloud2 docker/registry[4145]: time="2016-07-27T05:34:52.218938411Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=500ms, headers=map[]" go.version=go1.6.1 instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:34:52 cloud2 docker/registry[4145]: time="2016-07-27T05:34:52.219030671Z" level=info msg="redis not configured" go.version=go1.6.1 instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:34:52 cloud2 docker/registry[4145]: time="2016-07-27T05:34:52.248371204Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.1 instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:34:52 cloud2 docker/registry[4145]: time="2016-07-27T05:34:52.248675851Z" level=debug msg="configured \"token\" access controller" go.version=go1.6.1 instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:34:52 cloud2 docker/registry[4145]: time="2016-07-27T05:34:52.248752258Z" level=info msg="listening on [::]:5000" go.version=go1.6.1 instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:35:49 cloud2 docker/registry[4145]: time="2016-07-27T05:35:49.946656371Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=2e861699-6cb2-42fa-9faf-a89aff8e871b http.request.method=GET http.request.remoteaddr="172.17.0.3:37777" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:35:49 cloud2 docker/registry[4145]: time="2016-07-27T05:35:49.94690752Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=2e861699-6cb2-42fa-9faf-a89aff8e871b http.request.method=GET http.request.remoteaddr="172.17.0.3:37777" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:35:49 cloud2 docker/registry[4145]: 172.17.0.3 - - [27/Jul/2016:05:35:49 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Go-http-client/1.1"
Jul 27 13:35:50 cloud2 docker/registry[4145]: time="2016-07-27T05:35:50.141125933Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=0a641e22-7e3f-4580-85ad-1b141689c681 http.request.method=GET http.request.remoteaddr="172.17.0.3:37778" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:35:50 cloud2 docker/registry[4145]: time="2016-07-27T05:35:50.160938299Z" level=debug msg="filesystem.List(\"/docker/registry/v2/repositories\")" auth.user.name=admin go.version=go1.6.1 http.request.host="registry:5000" http.request.id=0a641e22-7e3f-4580-85ad-1b141689c681 http.request.method=GET http.request.remoteaddr="172.17.0.3:37778" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry trace.duration=66.978µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=baa4f1cd-270a-4e93-a74f-89228541eed8 trace.line=150 version=v2.4.0 
Jul 27 13:35:50 cloud2 docker/registry[4145]: time="2016-07-27T05:35:50.161097537Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=0a641e22-7e3f-4580-85ad-1b141689c681 http.request.method=GET http.request.remoteaddr="172.17.0.3:37778" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=22.051687ms http.response.status=200 http.response.written=20 instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:35:50 cloud2 docker/registry[4145]: 172.17.0.3 - - [27/Jul/2016:05:35:50 +0000] "GET /v2/_catalog?n=1000 HTTP/1.1" 200 20 "" "Go-http-client/1.1"
Jul 27 13:47:01 cloud2 docker/registry[4145]: time="2016-07-27T05:47:01.631525742Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=8ec016c4-9915-4b3b-b873-e881f4ec863b http.request.method=GET http.request.remoteaddr="172.17.0.3:37990" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:47:01 cloud2 docker/registry[4145]: time="2016-07-27T05:47:01.631667031Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=8ec016c4-9915-4b3b-b873-e881f4ec863b http.request.method=GET http.request.remoteaddr="172.17.0.3:37990" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:47:01 cloud2 docker/registry[4145]: 172.17.0.3 - - [27/Jul/2016:05:47:01 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Go-http-client/1.1"
Jul 27 13:47:01 cloud2 docker/registry[4145]: time="2016-07-27T05:47:01.794026714Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=76012705-68cf-4f6b-9e52-1ac232425ccd http.request.method=GET http.request.remoteaddr="172.17.0.3:37991" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:47:01 cloud2 docker/registry[4145]: time="2016-07-27T05:47:01.795004143Z" level=debug msg="filesystem.List(\"/docker/registry/v2/repositories\")" auth.user.name=admin go.version=go1.6.1 http.request.host="registry:5000" http.request.id=76012705-68cf-4f6b-9e52-1ac232425ccd http.request.method=GET http.request.remoteaddr="172.17.0.3:37991" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry trace.duration=46.165µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=8e8a9057-e25d-489c-a12f-ca6114d3b671 trace.line=150 version=v2.4.0 
Jul 27 13:47:01 cloud2 docker/registry[4145]: time="2016-07-27T05:47:01.795128181Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=76012705-68cf-4f6b-9e52-1ac232425ccd http.request.method=GET http.request.remoteaddr="172.17.0.3:37991" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.367956ms http.response.status=200 http.response.written=20 instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:47:01 cloud2 docker/registry[4145]: 172.17.0.3 - - [27/Jul/2016:05:47:01 +0000] "GET /v2/_catalog?n=1000 HTTP/1.1" 200 20 "" "Go-http-client/1.1"
Jul 27 13:55:57 cloud2 docker/registry[4145]: time="2016-07-27T05:55:57.703740735Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host=159.99.93.147 http.request.id=7e167c89-d218-4fc6-bb91-5cbfff469b0e http.request.method=GET http.request.remoteaddr=159.99.105.146 http.request.uri="/v2/" http.request.useragent="Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:55:57 cloud2 docker/registry[4145]: time="2016-07-27T05:55:57.703831948Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.1 http.request.host=159.99.93.147 http.request.id=7e167c89-d218-4fc6-bb91-5cbfff469b0e http.request.method=GET http.request.remoteaddr=159.99.105.146 http.request.uri="/v2/" http.request.useragent="Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" instance.id=8f347640-fd44-4911-8296-9404769b974d service=registry version=v2.4.0 
Jul 27 13:55:57 cloud2 docker/registry[4145]: 172.17.0.7 - - [27/Jul/2016:05:55:57 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
Jul 27 14:15:08 cloud2 docker/registry[4145]: time="2016-07-27T06:15:08.711766017Z" level=info msg="debug server listening localhost:5001" 
Jul 27 14:15:08 cloud2 docker/registry[4145]: time="2016-07-27T06:15:08.71326544Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=500ms, headers=map[]" go.version=go1.6.1 instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:15:08 cloud2 docker/registry[4145]: time="2016-07-27T06:15:08.713367897Z" level=info msg="redis not configured" go.version=go1.6.1 instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:15:08 cloud2 docker/registry[4145]: time="2016-07-27T06:15:08.745427421Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.1 instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:15:08 cloud2 docker/registry[4145]: time="2016-07-27T06:15:08.745733116Z" level=debug msg="configured \"token\" access controller" go.version=go1.6.1 instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:15:08 cloud2 docker/registry[4145]: time="2016-07-27T06:15:08.745804494Z" level=info msg="listening on [::]:5000" go.version=go1.6.1 instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:16:22 cloud2 docker/registry[4145]: time="2016-07-27T06:16:22.65807218Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host=159.99.93.147 http.request.id=d07f9096-ccde-4981-a6bb-74507a1a2ab0 http.request.method=GET http.request.remoteaddr=159.99.105.146 http.request.uri="/v2/" http.request.useragent="Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:16:22 cloud2 docker/registry[4145]: time="2016-07-27T06:16:22.658281704Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.1 http.request.host=159.99.93.147 http.request.id=d07f9096-ccde-4981-a6bb-74507a1a2ab0 http.request.method=GET http.request.remoteaddr=159.99.105.146 http.request.uri="/v2/" http.request.useragent="Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:16:22 cloud2 docker/registry[4145]: 172.17.0.7 - - [27/Jul/2016:06:16:22 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
Jul 27 14:22:04 cloud2 docker/registry[4145]: time="2016-07-27T06:22:04.442152483Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=28b61ef4-c839-4b10-be76-c4815372f285 http.request.method=GET http.request.remoteaddr="172.17.0.3:38745" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:22:04 cloud2 docker/registry[4145]: time="2016-07-27T06:22:04.44229433Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=28b61ef4-c839-4b10-be76-c4815372f285 http.request.method=GET http.request.remoteaddr="172.17.0.3:38745" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:22:04 cloud2 docker/registry[4145]: 172.17.0.3 - - [27/Jul/2016:06:22:04 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Go-http-client/1.1"
Jul 27 14:22:04 cloud2 docker/registry[4145]: time="2016-07-27T06:22:04.628528139Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=a010beac-2575-4fbc-b0ee-4b7faec31e41 http.request.method=GET http.request.remoteaddr="172.17.0.3:38746" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:22:04 cloud2 docker/registry[4145]: time="2016-07-27T06:22:04.629617104Z" level=debug msg="filesystem.List(\"/docker/registry/v2/repositories\")" auth.user.name=admin go.version=go1.6.1 http.request.host="registry:5000" http.request.id=a010beac-2575-4fbc-b0ee-4b7faec31e41 http.request.method=GET http.request.remoteaddr="172.17.0.3:38746" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry trace.duration=52.241µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=a45cee2b-244d-4450-b3e4-cf8efa299a26 trace.line=150 version=v2.4.0 
Jul 27 14:22:04 cloud2 docker/registry[4145]: time="2016-07-27T06:22:04.629769428Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=a010beac-2575-4fbc-b0ee-4b7faec31e41 http.request.method=GET http.request.remoteaddr="172.17.0.3:38746" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.553385ms http.response.status=200 http.response.written=20 instance.id=a9f46a96-1daf-4647-bec5-da1b240e4979 service=registry version=v2.4.0 
Jul 27 14:22:04 cloud2 docker/registry[4145]: 172.17.0.3 - - [27/Jul/2016:06:22:04 +0000] "GET /v2/_catalog?n=1000 HTTP/1.1" 200 20 "" "Go-http-client/1.1"
Jul 27 14:59:24 cloud2 docker/registry[20912]: time="2016-07-27T06:59:24.273538571Z" level=info msg="debug server listening localhost:5001" 
Jul 27 14:59:24 cloud2 docker/registry[20912]: time="2016-07-27T06:59:24.274913815Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=500ms, headers=map[]" go.version=go1.6.1 instance.id=84fabed9-a4fc-499f-8adc-88cb050283c1 service=registry version=v2.4.0 
Jul 27 14:59:24 cloud2 docker/registry[20912]: time="2016-07-27T06:59:24.275024025Z" level=info msg="redis not configured" go.version=go1.6.1 instance.id=84fabed9-a4fc-499f-8adc-88cb050283c1 service=registry version=v2.4.0 
Jul 27 14:59:24 cloud2 docker/registry[20912]: time="2016-07-27T06:59:24.306136361Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.1 instance.id=84fabed9-a4fc-499f-8adc-88cb050283c1 service=registry version=v2.4.0 
Jul 27 14:59:24 cloud2 docker/registry[20912]: time="2016-07-27T06:59:24.30641866Z" level=debug msg="configured \"token\" access controller" go.version=go1.6.1 instance.id=84fabed9-a4fc-499f-8adc-88cb050283c1 service=registry version=v2.4.0 
Jul 27 14:59:24 cloud2 docker/registry[20912]: time="2016-07-27T06:59:24.306484031Z" level=info msg="listening on [::]:5000" go.version=go1.6.1 instance.id=84fabed9-a4fc-499f-8adc-88cb050283c1 service=registry version=v2.4.0 
Jul 27 14:59:45 cloud2 docker/registry[20912]: time="2016-07-27T06:59:45.3935113Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=e35bb8a4-4cdf-4d23-b38d-d1b72a95f750 http.request.method=GET http.request.remoteaddr="172.17.0.6:42535" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=84fabed9-a4fc-499f-8adc-88cb050283c1 service=registry version=v2.4.0 
Jul 27 14:59:45 cloud2 docker/registry[20912]: time="2016-07-27T06:59:45.393737166Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=e35bb8a4-4cdf-4d23-b38d-d1b72a95f750 http.request.method=GET http.request.remoteaddr="172.17.0.6:42535" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=84fabed9-a4fc-499f-8adc-88cb050283c1 service=registry version=v2.4.0 
Jul 27 14:59:45 cloud2 docker/registry[20912]: 172.17.0.6 - - [27/Jul/2016:06:59:45 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "Go-http-client/1.1"
Jul 27 14:59:45 cloud2 docker/registry[20912]: time="2016-07-27T06:59:45.558427383Z" level=debug msg="authorizing request" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=c45eb1d6-d015-4baa-ac55-5acc01d87629 http.request.method=GET http.request.remoteaddr="172.17.0.6:42536" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" instance.id=84fabed9-a4fc-499f-8adc-88cb050283c1 service=registry version=v2.4.0 
Jul 27 14:59:45 cloud2 docker/registry[20912]: time="2016-07-27T06:59:45.559346075Z" level=debug msg="filesystem.List(\"/docker/registry/v2/repositories\")" auth.user.name=admin go.version=go1.6.1 http.request.host="registry:5000" http.request.id=c45eb1d6-d015-4baa-ac55-5acc01d87629 http.request.method=GET http.request.remoteaddr="172.17.0.6:42536" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" instance.id=84fabed9-a4fc-499f-8adc-88cb050283c1 service=registry trace.duration=47.772µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=3185e901-23e9-4d7a-bee0-a896d473510d trace.line=150 version=v2.4.0 
Jul 27 14:59:45 cloud2 docker/registry[20912]: time="2016-07-27T06:59:45.55946704Z" level=info msg="response completed" go.version=go1.6.1 http.request.host="registry:5000" http.request.id=c45eb1d6-d015-4baa-ac55-5acc01d87629 http.request.method=GET http.request.remoteaddr="172.17.0.6:42536" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.893035ms http.response.status=200 http.response.written=20 instance.id=84fabed9-a4fc-499f-8adc-88cb050283c1 service=registry version=v2.4.0 
Jul 27 14:59:45 cloud2 docker/registry[20912]: 172.17.0.6 - - [27/Jul/2016:06:59:45 +0000] "GET /v2/_catalog?n=1000 HTTP/1.1" 200 20 "" "Go-http-client/1.1"

**Comment by chowyu08** [comment] 2016-07-27 07:45
log file

**Comment by reasonerjt** [comment] 2016-07-27 10:30
are you using https or http on the nginx?

**Comment by jmccann** [comment] 2016-07-27 14:39
I'm having similar issues.  Commented in #130

**Comment by chowyu08** [comment] 2016-07-28 00:36
@reasonerjt  yes , I use https in nginx

**Comment by reasonerjt** [comment] 2016-07-28 03:32
@chowyu08 
There's issue in your cert so the golang failed to validate your cert, for details see this:
https://github.com/docker/docker/issues/8943

**Comment by chowyu08** [comment] 2016-07-28 04:07
@reasonerjt I do as https://github.com/vmware/harbor/blob/master/docs/configure_https.md

**Comment by reasonerjt** [comment] 2016-07-28 06:02
Did you do this:

2) Generate a Certificate Signing Request, be sure to use reg.yourdomain.com as the CN (Common Name):

  openssl req \
    -newkey rsa:4096 -nodes -sha256 -keyout yourdomain.com.key \
    -out yourdomain.com.csr

**Comment by reasonerjt** [comment] 2016-07-28 06:04
And did you properly configure the docker client?

**Comment by reasonerjt** [comment] 2016-07-28 06:05
The doc is just a workaround to help user get the idea, if you are serious about ssl you certainly need a CA cert, not self-signed cert.

**Comment by chowyu08** [comment] 2016-07-28 08:04
@reasonerjt  yes I have generated a Certificate Signing Request, what the docker client configure? add "--insecure-registry="?

**Comment by reasonerjt** [comment] 2016-07-28 12:00
No, for self signed cert you need to put it under /etc/docker/cert.d/, for details see:
https://docs.docker.com/engine/security/certificates/

**Comment by chowyu08** [comment] 2016-07-29 01:38
@reasonerjt I do as https://docs.docker.com/engine/security/certificates/
but new error.
![image](https://cloud.githubusercontent.com/assets/16483518/17234994/41afbb0a-5570-11e6-8148-652f85a18bd0.png)

**Comment by reasonerjt** [comment] 2016-07-29 07:10
Could you use openssl to inspect the CN of your cert on nginx and put the result in the issue?

**Comment by reasonerjt** [comment] 2016-07-29 11:54
@chowyu08 this maybe due to a change in the implementation, the doc may need to be revised give me a few more days and we'll confirm

**Comment by reasonerjt** [comment] 2016-07-31 10:24
@chowyu08 
The root cause is you are using IP to access not hostname.
In the document the setting only works if you are using FQDN to access registry, if you are using IP you need to set IP SAN in the cert.
As for now, please follow the steps:
http://stackoverflow.com/questions/21488845/how-can-i-generate-a-self-signed-certificate-with-subjectaltname-using-openssl

**Comment by wemeya** [comment] 2016-08-10 04:26
@chowyu08 
We've updated the configure_https.md. You can redo your job according to the doc. If any questions, pls feed back.

**Comment by chowyu08** [comment] 2016-08-11 00:50
@wemeya  ,thanks

**Comment by wemeya** [comment] 2016-09-07 03:31
@chowyu08 

If no question, pls close the issue, or we'll close it later. You're welcome and feel free to reopen it if you have further questions .

**Closed** 2016-09-12 06:50 UTC
