### ISSUE TITLE
logout and login will get a useless page,need refresh

### ISSUE THREAD

**Issue by sigsbee** [vmware/harbor#1697] opened 2017-03-21 02:37 UTC
when admin user logout and login again, will get a page not work, 
![error](https://cloud.githubusercontent.com/assets/23101283/24130230/4ebd2646-0e22-11e7-8ab8-89fa703ef678.PNG)

need to refresh to get the right page
![refesh](https://cloud.githubusercontent.com/assets/23101283/24130242/5a6ad560-0e22-11e7-81da-00d8c271f24b.PNG)
firefox esr 45.8.0

**Comment by steven-zou** [comment] 2017-03-21 12:56
Will close the search result panel when logout

**Comment by steven-zou** [comment] 2017-03-21 12:56
Seem duplicated issue with #1693

**Comment by steven-zou** [comment] 2017-03-23 02:10
Confirmed, duplicated issue with #1693 and caused by Clarity issue https://github.com/vmware/clarity/issues/625.

Will close this issue use #1693 to track the bug.

**Closed by steven-zou** 2017-03-23 02:10 UTC
Labels: area/clarity-ui
