### ISSUE TITLE
push image without namespace failed

### ISSUE THREAD

**Issue by cmingxu** [vmware/harbor#56] opened 2016-03-29 03:37 UTC
Login as admin and try to push a image failed, got "insufficient scope" from registry/distribution. Here is the command that I use to push 

 docker push 192.168.99.100/ubuntu:v0.4

the project/namespace where I am trying to push to is the **library** project under admin account, I supposed to have the write permission. When I dig into the harbor code I find 
https://github.com/vmware/harbor/blob/master/service/utils/authutils.go#L66

Obviously, harbor intentionally omit this kind to scenario , I want know is this a bug or not?  

thanks

**Comment by reasonerjt** [comment] 2016-03-29 04:10
It's not a bug, the design is you need to explicitly set the namespace in push command, in your case:
docker push 192.168.99.100/**library**/ubuntu:v0.4

the library was added by docker client when trying to pull images from docker hub.

So you  even can update the code to check against project "library" when the namespace is not set, but I think the pull will fail, as it will trigger API on registry and registry will not add this "default" namespace

**Comment by cmingxu** [comment] 2016-03-30 01:28
@reasonerjt  make sense to me, thanks for the response

**Comment by reasonerjt** [comment] 2016-03-30 05:14
@cmingxu Thanks, I'm closing the issue along with the PR.

**Closed by reasonerjt** 2016-03-30 05:14 UTC
