### ISSUE TITLE
pushing an image to non-existing project give a wrong error "unauthorized: authentication required"

### ISSUE THREAD

**Issue by mobla** [vmware/harbor#966] opened 2016-10-28 00:13 UTC
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose
vic - build: 6302
2)Config files of harbor, you can get them by packaging "Deploy/config" directory
Attached:
3)Log files, you can get them by package the /var/log/harbor/ 
Attached

Steps:
a. docker pull vmware/powerclicore
b. docker login 10.139.23.226:80
c. docker tag vmware/powerclicore 10.139.23.226:80/heimdall/vmware/powerclicore:latest
Note: mistakenly tagged the image with /heimdall/vmware/ instead of /heimdall - which is a project in Harbor (heimdall/vmware doesn't exist)
d. docker push 10.139.23.226:80/heimdall/vmware/powerclicore:latest

Expected error message should be project heimdall/vmware does not exist! but it fails with "unauthorized: authentication required"

root@photon-lJUA39j42 [ ~/vic ]# docker push 10.139.23.226:80/heimdall/vmware/powerclicore:latest
The push refers to a repository [10.139.23.226:80/heimdall/vmware/powerclicore]
01202148d0f6: Preparing
e76075d4e292: Preparing
bcd159fe40d2: Preparing
07f3dbba38e9: Preparing
07f25c3a9624: Preparing
e514b9b4f95d: Waiting
06d638613b1f: Waiting
9eaa66104bcd: Waiting
3f8edb08d1c3: Waiting
59b7f1d4aec2: Waiting
5f70bf18a086: Waiting
1c00945df04e: Waiting
unauthorized: authentication required
## Harbor Log snippet:

Oct 28 00:00:18 172.18.0.1 docker/ui[837]: 2016-10-28T00:00:18Z [DEBUG] [token.go:53]: uid for logging: admin
Oct 28 00:00:18 172.18.0.1 docker/ui[837]: 2016-10-28T00:00:18Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is db_auth
Oct 28 00:00:18 172.18.0.1 docker/ui[837]: 2016-10-28T00:00:18Z [DEBUG] [token.go:63]: username for filtering access: admin.
Oct 28 00:00:18 172.18.0.1 docker/ui[837]: 2016-10-28T00:00:18Z [INFO] project heimdall/vmware does not exist, set empty permission for admin
Oct 28 00:00:18 172.18.0.1 docker/ui[837]: 2016-10-28T00:00:18Z [INFO] current access, type: repository, name:heimdall/vmware/powerclicore, actions:[]
Oct 28 00:00:18 172.18.0.1 docker/ui[837]: 2016-10-28T00:00:18Z [INFO] current access, type: repository, name:heimdall/nginx, actions:[push \* pull]

**Comment by reasonerjt** [comment] 2016-10-30 16:26
@mobla This may be not very good user experience but it's working as design.
However the way Harbor works is that our code only provide a token to docker client, who then use this token to access registry to try to push the image.

In the case the project does not exist, the token will not contain the permission to push and registry will return 401, so docker client displays "authentication failed".
I don't think there's way to customize the error message of docker client in such model.
I'll keep this issue open but mark it as "limitation".  We'll explore if there's a way to fix this, but not this release.

**Comment by reasonerjt** [comment] 2018-07-26 02:57
Closing as by design.

**Closed by reasonerjt** 2018-07-26 02:57 UTC
Labels: kind/limitation
