### ISSUE TITLE
执行pull的时候，显示两次，it shows twice after I pull the image

### ISSUE THREAD

**Issue by zhangzongjun** [vmware/harbor#1495] opened 2017-03-02 02:27 UTC
################################
system version: centos 7.3 kernel:3.10
docker version: 1.12.5
harbor version: 0.5.0
################################
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [authenticator.go:57]: Current AUTH_MODE is db_auth
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [token.go:63]: username for filtering access: admin.
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [INFO] current access, type: repository, name:test/busybox, actions:[push * pull]
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017/03/02 09:34:04 #033[1;34m[router.go:829][D] | GET        | /service/token                           | 63.247978ms      | match  | /service/token                           | #033[0m
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [authutils.go:49]: scopes: [repository:test/busybox:pull]
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [INFO] request url: /service/token?account=admin&scope=repository%3Atest%2Fbusybox%3Apull&service=token-service
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [WARNING] Failed to get secret cookie, error: http: named cookie not present
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [token.go:53]: uid for logging: admin
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [authenticator.go:57]: Current AUTH_MODE is db_auth
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [notification.go:107]: receive an event:
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----ID: f531bc03-294f-402f-bd0c-313326f386e4
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----target: test/busybox:latest
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----digest: sha256:2efce9f5b0cb8815d192ae634b4c87943d0f0b873d98487ee98f8ed0504bd572
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----action: pull
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----mediatype: application/vnd.docker.distribution.manifest.v2+json
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----user-agent: docker/1.12.5 go/go1.7.4 kernel/3.10.0-514.6.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.5 \(linux\))
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [notification.go:123]: add event to collect: f531bc03-294f-402f-bd0c-313326f386e4
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017/03/02 09:34:04 #033[1;34m[router.go:829][D] | POST       | /service/notifications                   | 649.228µs        | match  | /service/notifications                   | #033[0m
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [notification.go:93]: Increase the repository test/busybox pull count.
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [token.go:63]: username for filtering access: admin.
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [INFO] current access, type: repository, name:test/busybox, actions:[push * pull]
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017/03/02 09:34:04 #033[1;34m[router.go:829][D] | GET        | /service/token                           | 63.042674ms      | match  | /service/token                           | #033[0m
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [notification.go:107]: receive an event:
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----ID: 8658a033-a167-4d3d-9783-a7e52080a1c9
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----target: test/busybox:
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----digest: sha256:2efce9f5b0cb8815d192ae634b4c87943d0f0b873d98487ee98f8ed0504bd572
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----action: pull
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----mediatype: application/vnd.docker.distribution.manifest.v2+json
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: ----user-agent: docker/1.12.5 go/go1.7.4 kernel/3.10.0-514.6.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.5 \(linux\))
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [notification.go:123]: add event to collect: 8658a033-a167-4d3d-9783-a7e52080a1c9
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017/03/02 09:34:04 #033[1;34m[router.go:829][D] | POST       | /service/notifications                   | 600.709µs        | match  | /service/notifications                   | #033[0m
Mar  2 09:34:04 172.18.0.1 harbor-ui[1334]: 2017-03-02T09:34:04+08:00 [DEBUG] [notification.go:93]: Increase the repository test/busybox pull count.

**Comment by zhangzongjun** [comment] 2017-03-02 02:32
Mar 2 09:34:04 172.18.0.1 harbor-ui[1334]: ----ID: f531bc03-294f-402f-bd0c-313326f386e4
Mar 2 09:34:04 172.18.0.1 harbor-ui[1334]: ----target: test/busybox:latest
Mar 2 09:34:04 172.18.0.1 harbor-ui[1334]: ----digest: sha256:2efce9f5b0cb8815d192ae634b4c87943d0f0b873d98487ee98f8ed0504bd572
Mar 2 09:34:04 172.18.0.1 harbor-ui[1334]: ----action: pull

**Comment by zhangzongjun** [comment] 2017-03-02 02:34
when I pull some image that I have pushed. In the web page, it will show two times about the pull action.

**Comment by reasonerjt** [comment] 2017-03-02 02:41
Looks like the registry client did something that confused the notification?  @ywk253100   Is it fixed in dev branch?

**Comment by reasonerjt** [comment] 2017-03-02 04:32
ah my bad, in second notification the user-agent is also docker, so not the registry client, let's try to reproduce and investigate.

**Comment by zhangzongjun** [comment] 2017-03-02 06:03
@reasonerjt  I hope you can help me to resolve this problem as soon as possible, thx very much!

**Comment by ywk253100** [comment] 2017-03-02 10:10
Provide the log of proxy.

**Comment by zhangzongjun** [comment] 2017-03-03 00:26
admin	test/busybox		        pull	2017-03-03 08:24:17
admin	test/busybox	latest	pull	2017-03-03 08:24:17

My proxy log as follow:
Mar  3 08:24:17 172.18.0.1 harbor-proxy[10460]: 10.207.0.6 - - [03/Mar/2017:08:24:17 +0800] "\x16\x03\x01\x00w\x01\x00\x00s\x03\x03r%\xD3KWT\xBC\x1BJ~I\xC3mz_ \xCBb\xF0U\xCF3\x91\xEF\x1E\x1F\xAE\xB2\xD5`\xB9\x17\x00\x00\x14\xC0,\xC00\xC0+\xC0/\xC0" 400 173 "-" "-"
Mar  3 08:24:17 172.18.0.1 harbor-proxy[10460]: 10.207.0.6 - - [03/Mar/2017:08:24:17 +0800] "GET /v2/ HTTP/1.1" 401 87 "-" "docker/1.12.5 go/go1.7.4 kernel/3.10.0-514.6.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.5 \x5C(linux\x5C))"
Mar  3 08:24:17 172.18.0.1 harbor-proxy[10460]: 10.207.0.6 - - [03/Mar/2017:08:24:17 +0800] "\x16\x03\x01\x00\x7F\x01\x00\x00{\x03\x03\x910[\xCE\xB4\xD9l\xCD\x80\xE8}\x92\xD7(\x01\x80A\x09\xBF\x9Df\x15\xE8\xF9 \xDC\xAB\xCE\x1F\xE5\xCC<\x00\x00\x1C\xC0/\xC0+\xC00\xC0,\xC0\x13\xC0\x09\xC0\x14\xC0" 400 173 "-" "-"
Mar  3 08:24:17 172.18.0.1 harbor-proxy[10460]: 10.207.0.6 - - [03/Mar/2017:08:24:17 +0800] "GET /v2/ HTTP/1.1" 401 87 "-" "docker/1.12.5 go/go1.7.4 kernel/3.10.0-514.6.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.5 \x5C(linux\x5C))"
Mar  3 08:24:17 172.18.0.1 harbor-proxy[10460]: 10.207.0.6 - - [03/Mar/2017:08:24:17 +0800] "GET /v2/test/busybox/manifests/latest HTTP/1.1" 401 144 "-" "docker/1.12.5 go/go1.7.4kernel/3.10.0-514.6.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.5 \x5C(linux\x5C))"
Mar  3 08:24:17 172.18.0.1 harbor-proxy[10460]: 10.207.0.6 - admin [03/Mar/2017:08:24:17 +0800] "GET /service/token?scope=repository%3Atest%2Fbusybox%3Apull&service=token-serviceHTTP/1.1" 200 1194 "-" "Go-http-client/1.1"
Mar  3 08:24:17 172.18.0.1 harbor-proxy[10460]: 10.207.0.6 - - [03/Mar/2017:08:24:17 +0800] "GET /v2/test/busybox/manifests/latest HTTP/1.1" 200 527 "-" "docker/1.12.5 go/go1.7.4kernel/3.10.0-514.6.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.5 \x5C(linux\x5C))"
Mar  3 08:24:17 172.18.0.1 harbor-proxy[10460]: 10.207.0.6 - admin [03/Mar/2017:08:24:17 +0800] "GET /service/token?account=admin&scope=repository%3Atest%2Fbusybox%3Apull&service=token-service HTTP/1.1" 200 1194 "-" "docker/1.12.5 go/go1.7.4 kernel/3.10.0-514.6.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.5 \x5C(linux\x5C))"
Mar  3 08:24:17 172.18.0.1 harbor-proxy[10460]: 10.207.0.6 - - [03/Mar/2017:08:24:17 +0800] "GET /v2/test/busybox/manifests/sha256:2efce9f5b0cb8815d192ae634b4c87943d0f0b873d98487ee98f8ed0504bd572 HTTP/1.1" 200 527 "-" "docker/1.12.5 go/go1.7.4 kernel/3.10.0-514.6.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.5 \x5C(linux\x5C))"
##################
Can you get some useful information?

**Comment by zhangzongjun** [comment] 2017-03-03 00:32
@ywk253100  If you want more information, I can provide what you want.

**Comment by ywk253100** [comment] 2017-03-03 00:54
It seems that something is wrong with your docker client.
When you pulled the test/busybox:latest, Harbor received the request twice, one was GET /v2/test/busybox/manifests/latest and the other one was GET /v2/test/busybox/manifests/sha256:2efce9f5b0cb8815d192ae634b4c87943d0f0b873d98487ee98f8ed0504bd572.

**Comment by zhangzongjun** [comment] 2017-03-03 01:00
@ywk253100 
Is there a problem with my docker client? What would you say if I change another docker client? And I want to have a try.

**Comment by ywk253100** [comment] 2017-03-03 02:54
You can try it.

**Comment by zhangzongjun** [comment] 2017-03-03 05:52
@ywk253100   
I'm so exciting, it's ok after I chaged the version of docker, I really appreciate of you!

**Comment by reasonerjt** [comment] 2017-03-03 06:14
Thanks guys, I'm closing this issue.

**Closed by reasonerjt** 2017-03-03 06:14 UTC
