### ISSUE TITLE
Support get the description of image on harbor

### ISSUE THREAD

**Issue by huzhengchuan** [vmware/harbor#3685] opened 2017-11-24 02:38 UTC
/KInd: Feature
/version: harbor1.2
/actual:cannot get the description of image on harbor
/expect: on harbor can get the description of image

**Comment by reasonerjt** [comment] 2017-11-27 01:58
@ninjadq please dup this issue as it's being worked on.

**Comment by ninjadq** [comment] 2017-12-14 11:40
Duplicate of #3217

**Closed** 2017-12-14 11:40 UTC
