### ISSUE TITLE
Configure certificate for Docker Cli cannot be shared with Notary Cli

### ISSUE THREAD

**Issue by wknet123** [vmware/harbor#1583] opened 2017-03-14 03:54 UTC
After put certificate into `/etc/docker/cert.d` to make HTTPS access with Docker, but it'll still need to put the certificate into OS level (`/usr/local/shared/ca-certificates/`) when integrate with Notary and it would be failed by using `update-ca-certificate` command.

**Comment by reasonerjt** [comment] 2017-03-14 04:48
using update-ca-certificate failed should be an issue of ubuntu, can be worked around by using "dpkg-reconfigure ca-certificates"  however I'll check why putting the cert under ```/etc/docker/cert.d``` didn't work.

Thanks for raising this issue.

**Comment by reasonerjt** [comment] 2017-03-14 09:52
Checked the code, when communicating with notary, docker will load the certs from a different directory, by default it's:
```~/.docker/tls/${hostname}/```

After copying the ca cert to this directory the issue's fixed.

I agree this is confusing, will keep this open and check with docker if this is by design or known issue.

**Comment by reasonerjt** [comment] 2017-03-27 03:02
This is the design, I've mentioned it in the doc, closing this issue.

**Closed by reasonerjt** 2017-03-27 03:02 UTC
Labels: area/notary-integration, limitation
