### ISSUE TITLE
Have pagination for the Users in Harbor

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2280] opened 2017-05-10 09:06 UTC
As per the scale, we need to have 1000 unique users created on harbor and upon creating 350 users I noticed that we are listing all users in one single page. Having pagination for Users will be helpful. Please consider this as feature enhancement request.

**Comment by ywk253100** [comment] 2017-05-10 10:33
Duplicate of #2206 .

**Closed by ywk253100** 2017-05-10 10:33 UTC
