### ISSUE TITLE
Call Repository API problem,  with the authenticated user, it won't return the private project detail.

### ISSUE THREAD

**Issue by linkmancheng** [vmware/harbor#492] opened 2016-07-07 07:08 UTC
I try to call the harbor repositories API, if it use the Basic Auth, it won't return the image of the owner's projects when the project is not public.  When I switch this project to public, it will return the correct result.
It's not the expected behavior, right?

My URL is like this: http://xxx.xxx.xx/api/repositories?project_id=26

Thanks.

**Comment by ywk253100** [comment] 2016-07-07 07:47
Please provide the logs of ui and registry, you can find them in /var/log/harbor/.

**Comment by linkmancheng** [comment] 2016-07-07 08:09
No special info in the log.

Jul  7 04:05:01 172.18.0.1 docker/ui[29674]: 2016-07-07T08:05:01Z [INFO] Config path: /etc/ui/app.conf
Jul  7 04:05:01 172.18.0.1 docker/ui[29674]: 2016-07-07T08:05:01Z [DEBUG] [base.go:73]: db url: mysql:3306, db user: root
Jul  7 04:05:01 172.18.0.1 docker/ui[29674]: 2016-07-07T08:05:01Z [ERROR] [base.go:85]: failed to connect to db, retry after 2 seconds :dial tcp 172.18.0.3:3306: getsockopt: connection refused
Jul  7 04:05:03 172.18.0.1 docker/ui[29674]: 2016-07-07T08:05:03Z [INFO] User id: 1 already has its encrypted password.
Jul  7 04:05:03 172.18.0.1 docker/ui[29674]: 2016/07/07 08:05:03 #033[1;34m[asm_amd64.s:1998][I] http server Running on :80#033[0m
Jul  7 04:05:20 172.18.0.1 docker/ui[29674]: 2016/07/07 08:05:20 #033[1;34m[router.go:828][D] | GET        | /api/repositories                        | 3.076451ms       | match      | /api/repositories                        | #033[0m

**Comment by ywk253100** [comment] 2016-07-07 09:10
What status code did you get when calling the API ?

**Comment by linkmancheng** [comment] 2016-07-07 14:10
403 Forbidden.

**Comment by ywk253100** [comment] 2016-07-08 02:52
403 means the user has no role to the project. 
Could you show me the tables 'user' and 'project_member' in the mysql container? You can login the mysql by command 'mysql -h 172.28.0.4 -uroot -proot123', the '172.28.0.4' is the IP of your mysql container, you can find it by running 'docker inspect deploy_mysql_1'.

**Comment by linkmancheng** [comment] 2016-07-08 06:14
I can access via web page and get related resources, it means role should be right. So the authentication via web page session should be right.

**Comment by ywk253100** [comment] 2016-07-09 01:45
Which branch does you use? Could you provide the commit ID?

**Comment by linkmancheng** [comment] 2016-07-13 05:39
I used the docker image from Harbor website about a month ago. Can you reproduce it in your environment?

**Comment by ywk253100** [comment] 2016-07-15 09:37
I have tried Harbor version 0.1.0 and 0.1.1, and don't reproduce your error, could you upgrade your Harbor to the new version?

**Comment by ywk253100** [comment] 2016-09-06 02:35
Closing due to no further details provided.

**Closed by ywk253100** 2016-09-06 02:35 UTC
