### ISSUE TITLE
Updating tile configuration causes deployment error

### ISSUE THREAD

**Issue by jakedsouza** [vmware/harbor#3774] opened 2017-12-12 04:38 UTC
Harbor tile version `harbor-1.3.0-rc.21.pivotal` 

Steps to reproduce - 
- Deploy tile 
- Update something in the tile (I updated the certificate with a custom one) 
- Click apply 

Expected - Harbor should be updated/redeployed with new changes 

Actual - Deployment errors out and the VM is stopped 

**Note**  I was able to change the certificate once and update. This happened on the second and third tries
Error logs `om installation-log -id 4`  
```
{"type": "step_started", "id": "bosh_product.deploying"}
===== 2017-12-12 04:20:11 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty create-env /var/tempest/workspaces/default/deployments/bosh.yml"
Deployment manifest: '/var/tempest/workspaces/default/deployments/bosh.yml'
Deployment state: '/var/tempest/workspaces/default/deployments/bosh-state.json'

Started validating
  Validating release 'bosh'... Finished (00:00:01)
  Validating release 'bosh-vsphere-cpi'... Finished (00:00:00)
  Validating release 'uaa'... Finished (00:00:01)
  Validating release 'credhub'... Finished (00:00:00)
  Validating release 'bosh-system-metrics-server'... Finished (00:00:01)
  Validating release 'os-conf'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Validating stemcell... Finished (00:00:03)
Finished validating (00:00:08)
No deployment, stemcell or release changes. Skipping deploy.

Succeeded
===== 2017-12-12 04:20:21 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty create-env /var/tempest/workspaces/default/deployments/bosh.yml"; Duration: 10s; Exit Status: 0
{"type": "step_finished", "id": "bosh_product.deploying"}
{"type": "step_started", "id": "bosh.uploading_runtime_config_releases"}
===== 2017-12-12 04:20:21 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 upload-release /var/tempest/internal_releases/dns"
Using environment '30.0.0.2' as client 'ops_manager'

 100.00% 890.90 KB/s 0s
Task 13

Task 13 | 04:20:23 | Extracting release: Extracting release (00:00:00)
Task 13 | 04:20:23 | Verifying manifest: Verifying manifest (00:00:00)
Task 13 | 04:20:23 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 13 | 04:20:23 | Processing 6 existing packages: Processing 6 existing packages (00:00:00)
Task 13 | 04:20:23 | Processing 4 existing jobs: Processing 4 existing jobs (00:00:00)
Task 13 | 04:20:23 | Release has been created: bosh-dns/0.0.8+dev.1507766367 (00:00:00)

Task 13 Started  Tue Dec 12 04:20:23 UTC 2017
Task 13 Finished Tue Dec 12 04:20:23 UTC 2017
Task 13 Duration 00:00:00
Task 13 done

Succeeded
===== 2017-12-12 04:20:24 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 upload-release /var/tempest/internal_releases/dns"; Duration: 2s; Exit Status: 0
{"type": "step_finished", "id": "bosh.uploading_runtime_config_releases"}
{"type": "step_started", "id": "bosh.updating_runtime_config.ops_manager_dns_runtime"}
===== 2017-12-12 04:20:24 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 update-runtime-config --name=ops_manager_dns_runtime /tmp/ops_manager_dns_runtime.yml20171212-1490-597yi9"
Using environment '30.0.0.2' as client 'ops_manager'

Succeeded
===== 2017-12-12 04:20:24 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 update-runtime-config --name=ops_manager_dns_runtime /tmp/ops_manager_dns_runtime.yml20171212-1490-597yi9"; Duration: 0s; Exit Status: 0
{"type": "step_finished", "id": "bosh.updating_runtime_config.ops_manager_dns_runtime"}
{"type": "step_started", "id": "bosh.updating_cloud_config"}
===== 2017-12-12 04:20:24 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 update-cloud-config /tmp/cloud_config.yml20171212-1490-12151hg"
Using environment '30.0.0.2' as client 'ops_manager'

Succeeded
===== 2017-12-12 04:20:24 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 update-cloud-config /tmp/cloud_config.yml20171212-1490-12151hg"; Duration: 0s; Exit Status: 0
{"type": "step_finished", "id": "bosh.updating_cloud_config"}
{"type": "step_started", "id": "uaa_config.resetting"}
{"type": "step_finished", "id": "uaa_config.resetting"}
{"type": "step_started", "id": "upload_assets.uploading_stemcell.harbor-container-registry-33e798729d38a0b4b41d"}
===== 2017-12-12 04:20:24 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 upload-stemcell /var/tempest/stemcells/bosh-stemcell-3468-vsphere-esxi-ubuntu-trusty-go_agent.tgz"
Using environment '30.0.0.2' as client 'ops_manager'

Stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468' already exists.

Succeeded
===== 2017-12-12 04:20:24 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 upload-stemcell /var/tempest/stemcells/bosh-stemcell-3468-vsphere-esxi-ubuntu-trusty-go_agent.tgz"; Duration: 0s; Exit Status: 0
{"type": "step_finished", "id": "upload_assets.uploading_stemcell.harbor-container-registry-33e798729d38a0b4b41d"}
{"type": "step_started", "id": "upload_assets.uploading_releases.harbor-container-registry-33e798729d38a0b4b41d"}
===== 2017-12-12 04:20:24 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 upload-release /var/tempest/releases/harbor-v1.3.0-rc1-35-gbcb74dd-1.3.0-rc.21.tgz"
Using environment '30.0.0.2' as client 'ops_manager'

 100.00% 171.00 KB/s 0s
Task 14

Task 14 | 04:20:32 | Extracting release: Extracting release (00:00:00)
Task 14 | 04:20:32 | Verifying manifest: Verifying manifest (00:00:00)
Task 14 | 04:20:32 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 14 | 04:20:32 | Processing 6 existing packages: Processing 6 existing packages (00:00:00)
Task 14 | 04:20:32 | Processing 2 existing jobs: Processing 2 existing jobs (00:00:00)
Task 14 | 04:20:32 | Release has been created: harbor/v1.3.0-rc1-35-gbcb74dd-1.3.0-rc.21 (00:00:00)

Task 14 Started  Tue Dec 12 04:20:32 UTC 2017
Task 14 Finished Tue Dec 12 04:20:32 UTC 2017
Task 14 Duration 00:00:00
Task 14 done

Succeeded
===== 2017-12-12 04:20:37 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 upload-release /var/tempest/releases/harbor-v1.3.0-rc1-35-gbcb74dd-1.3.0-rc.21.tgz"; Duration: 12s; Exit Status: 0
{"type": "step_finished", "id": "upload_assets.uploading_releases.harbor-container-registry-33e798729d38a0b4b41d"}
{"type": "step_started", "id": "migrate_variables.migrating.harbor-container-registry-33e798729d38a0b4b41d"}
{"type": "step_finished", "id": "migrate_variables.migrating.harbor-container-registry-33e798729d38a0b4b41d"}
{"type": "step_started", "id": "bosh.deploying.harbor-container-registry-33e798729d38a0b4b41d"}
===== 2017-12-12 04:20:37 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 --deployment=harbor-container-registry-33e798729d38a0b4b41d deploy /var/tempest/workspaces/default/deployments/harbor-container-registry-33e798729d38a0b4b41d.yml"
Using environment '30.0.0.2' as client 'ops_manager'

Using deployment 'harbor-container-registry-33e798729d38a0b4b41d'

  instance_groups:
  - name: harbor-app
    properties:
      server_cert_key:
-       cert_and_private_key_pems: "<redacted>"
+       cert_and_private_key_pems: "<redacted>"
-       cert_pem: "<redacted>"
+       cert_pem: "<redacted>"
-       private_key_pem: "<redacted>"
+       private_key_pem: "<redacted>"
-       public_key_pem: "<redacted>"
+       public_key_pem: "<redacted>"
      ssl:
-       cert: "<redacted>"
+       cert: "<redacted>"
-       key: "<redacted>"
+       key: "<redacted>"
Task 15

Task 15 | 04:20:38 | Preparing deployment: Preparing deployment (00:00:02)
Task 15 | 04:20:40 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 15 | 04:20:40 | Updating instance harbor-app: harbor-app/027f4bfe-9273-4f37-9bba-8c3f08cf36a1 (0) (canary) (00:01:18)
                   L Error: Action Failed get_task: Task d9cb4ece-3f1f-41db-433f-01271cfb83db result: Stopping Monitored Services: Stopping services '[dockerd]' errored
Task 15 | 04:21:58 | Error: Action Failed get_task: Task d9cb4ece-3f1f-41db-433f-01271cfb83db result: Stopping Monitored Services: Stopping services '[dockerd]' errored

Task 15 Started  Tue Dec 12 04:20:38 UTC 2017
Task 15 Finished Tue Dec 12 04:21:58 UTC 2017
Task 15 Duration 00:01:20
Task 15 error


Updating deployment:
  Expected task '15' to succeed but state is 'error'
Exit code 1
===== 2017-12-12 04:21:58 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.2 --deployment=harbor-container-registry-33e798729d38a0b4b41d deploy /var/tempest/workspaces/default/deployments/harbor-container-registry-33e798729d38a0b4b41d.yml"; Duration: 80s; Exit Status: 1
{"type": "step_finished", "id": "bosh.deploying.harbor-container-registry-33e798729d38a0b4b41d"}
Exited with 1.
```

**Comment by jessehu** [comment] 2017-12-12 07:07
hi @jakedsouza, I tried to reproduce it by generating a new SSL Certificate and key PEMs several times, but didn't meet any issue. Do you still have your env for me to take a look ?

**Comment by jakedsouza** [comment] 2017-12-12 09:01
I think we can close this. I was testing with a certificate with a common name that was not the hostname. This was causing the issue in updating the deployment since the certificate was invalid. 

Repeating the process with an autogenerated cert or with a custom certificate with a valid common name and subject alternative name allowed the tile to get installed successfully.

**Comment by jessehu** [comment] 2017-12-12 09:19
Glad to know the root cause. Closing now. Thanks Jake.

**Closed by jessehu** 2017-12-12 09:19 UTC
Labels: area/bosh-release, area/tile, kind/bug, target/pks-0.8
