### ISSUE TITLE
No error message pops up when reset password by email if you use wrong email password during ova deployment

### ISSUE THREAD

**Issue by frankli0614** [vmware/harbor#1165] opened 2016-11-25 06:24 UTC
Harbor ova: 0.5.0 rc1

1. Deploy ova and use wrong password in Email Settings.
2. Login to Harbor with Admin and add a user with email frank@harbortest.cn.
3. Log out Harbor 
4. Click Forgot Password link
5. Input the user's email frank@harbortest.cn.
6. Click Send button

Actual Result: The reset password email doesn't send successfully. And there is no any error message or information pops up to indicate that the email send failed.

![email password verify](https://cloud.githubusercontent.com/assets/23302563/20616094/85c00644-b31a-11e6-8ddc-fe22d7036ae6.png)

Here is the email settings during ova deployment.
SMTP: smtp.exmail.qq.com
Port: 465
SSL: true
Email username: admin@harbortest.cn

**Comment by reasonerjt** [comment] 2016-11-25 09:31
The root cause is the server side returns 504, however ,uI need to show an explicit error, instead of failing silently.

**Comment by wknet123** [comment] 2016-11-25 09:35
Fixed with PR #1171

**Closed** 2016-11-28 06:07 UTC
