### ISSUE TITLE
Support displaying Dockerfile content in Harbor UI

### ISSUE THREAD

**Issue by qqian1991** [vmware/harbor#1191] opened 2016-11-30 07:50 UTC
We set up a Harbor in our virtual machine environment and build/push images to Harbor projects.

* But now we can only see some images basic information for this images
* Can we support push and upload the dockerfile to harbor and display it in a single page just like the Docker hub does.
* For the management of images, I think there are great benefits to display dockerfile

**Comment by reasonerjt** [comment] 2016-11-30 11:41
We may support adding description to the images, however, we may not support dockerfile as currently are not sure how to verify if the image and dockerfile matches.

**Comment by hainingzhang** [comment] 2016-12-01 13:52
duplicate of #1088 . close this for now.

**Closed by hainingzhang** 2016-12-01 13:52 UTC
