### ISSUE TITLE
Need to restart to see pushed images

### ISSUE THREAD

**Issue by AlexZeitler** [vmware/harbor#48] opened 2016-03-25 21:02 UTC
After pushing images to harbor, I have to run ```docker-compose kill``` and ```docker-compose up -d``` to see the new images. Search inside the UI also doesn't find them before restarting.

But I can pull the images using the Docker client without restarting.

**Comment by xiaods** [comment] 2016-03-28 04:41
i came across this issue, but i wait a moment, it will show the image. maybe something need update period.

**Comment by reasonerjt** [comment] 2016-03-28 05:48
There's a webhook in ui container to update the images in cache, it should not take more than a few seconds. @AlexZeitler, how long do you have to wait?  Could you attach the config.yml of registry? It's location is harbor/Deploy/config/registry/config.yml

**Comment by AlexZeitler** [comment] 2016-03-28 11:51
@reasonerjt I have been waiting for about 2 minutes.

`config.yml`:

```yml
version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /storage
    maintenance:
        uploadpurging:
            enabled: false
http:
    addr: :5000
    secret: placeholder
    debug:
        addr: localhost:5001
auth:
  token:
    issuer: registry-token-issuer
    realm: http://localhost/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service

notifications:
  endpoints:
      - name: harbor
        disabled: false
        url: http://localhost/service/notifications
        timeout: 500
        threshold: 5
        backoff: 1000
```

**Comment by reasonerjt** [comment] 2016-03-28 14:45
@AlexZeitler I see, in harbor.cfg you need to set the hostname with the IP of eth0 such as "192.168.0.2", not "localhost".
See the section of notifications, the registry will make http call to the "url", and since registry is running in a container and the /service/notofications/ is running in another process outside the container, the call will fail and the cache will not be updated.

**Comment by AlexZeitler** [comment] 2016-03-29 10:50
@reasonerjt Thanks, this did the trick! :+1: 

Just for the understanding: ```ui``` (which hosts ```/service/notifications```) and ```registry``` both run in containers and they're linked according to ```docker-compose.yml``` (at least ```ui``` can see ```registry```).

So if ```registry``` would also link ```ui``` it could access it by its IP which is exposed as an environment variable to the ```registry``` container.

Or if you switch to ```docker-compose``` 1.6+ you could just use the default network and access the containers by their names so ```http://ui/service/notifications``` should just work without setting even setting host or IP.

Is there a reason for not doing that? (sorry, I'm just beginning with golang...)

**Comment by reasonerjt** [comment] 2016-03-29 11:00
@AlexZeitler , thanks for your suggestion, I opened https://github.com/vmware/harbor/issues/59

**Comment by reasonerjt** [comment] 2016-03-30 10:26
Closing this issue and the problem is fixed.  further work will be tracked in #59

**Closed by reasonerjt** 2016-03-30 10:26 UTC
