### ISSUE TITLE
404 returned when calling harbor API

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#3734] opened 2017-12-03 03:48 UTC
Deploy Harbor with tile

Curl host/api/system 404 returned
Curl ui8080/api/system data returned 
docker ps
  starting timestamps of image containers may diff 1 min
The images might be started by compose in different times

**Comment by reasonerjt** [comment] 2017-12-03 04:58
Is it a tile only issue?

**Comment by reasonerjt** [comment] 2017-12-04 06:54
I can't reproduce in non-tile environment.
root cause for this issue is probably #3735

**Comment by reasonerjt** [comment] 2017-12-14 06:35
Closing as this seems a problem in bosh release, and it has been fixed.

**Closed by reasonerjt** 2017-12-14 06:35 UTC
Labels: area/deployment, area/tile, kind/bug
