### ISSUE TITLE
"docker pull" failed with "Retrying in xx second" and "unexpected EOF"

### ISSUE THREAD

**Issue by ccnupq** [vmware/harbor#3062] opened 2017-08-16 09:39 UTC
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.

```
# docker --version
Docker version 17.06.0-ce, build 02c1d87

# docker-compose --version
docker-compose version 1.14.0, build c7bdf9e
```

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.

```
#grep -v "^#" harbor.cfg  | grep -v "^$"

hostname = registry.example.com
ui_url_protocol = https
db_password = xxx
max_job_workers = 3 
customize_crt = off
ssl_cert = /home/xxx/harbor_cert/registry.example.com.cer
ssl_cert_key = /home/xxx/harbor_cert/registry.example.com.key
secretkey_path = /data
admiral_url = NA
clair_db_password = xxxxx
email_identity = 
email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false
harbor_admin_password = xxxxxx
auth_mode = db_auth
ldap_url = ldaps://ldap.mydomain.com
ldap_basedn = ou=people,dc=mydomain,dc=com
ldap_uid = uid 
ldap_scope = 3 
ldap_timeout = 5
self_registration = off
token_expiration = 30
project_creation_restriction = adminonly
verify_remote_cert = off
```

3)Log files, you can get them by package the /var/log/harbor/ .

[Harbor.error.log_2017-08-16.txt](https://github.com/vmware/harbor/files/1227720/Harbor.error.log_2017-08-16.txt)

---------------------
Issue reproduction steps

```
1.  on sever A
docker login   
success

2. from server A.  
docker push   
success

3. on server B
docker login 
success

4. docker push on server B
docker pull 
failed as follow:

1.0: Pulling from  xxxxxxxxxxx
9f0706ba7422: Retrying in 1 second 
d3942a742d22: Retrying in 1 second 
2b95a7bc6bf9: Downloading [==================================================>] 243.1 kB/243.1 kB
e4c7597bbbc1: Waiting 
5f5ed4ce77dc: Waiting 
63038208f189: Waiting 
1138b1f02201: Waiting 
f027013454f1: Waiting 
41cf8eaed89c: Waiting 
08038cdd003c: Waiting 
d4afc280bba7: Waiting 
a0416d3a601b: Waiting 
173941a1f6c9: Waiting 
unexpected EOF
```

This issue can be seen every time when "docker pull"

----------------
My docker image size is hundreds of MB or several GB. 
At last, I  found , in the Nginx templates, the proxy_max_temp_file_size is not set and its default value will cause above issue. so I made modification like this:

`proxy_max_temp_file_size 0;`

Then the issue was gone.

1.0: Pulling from xxxxxx
9f0706ba7422: Pull complete 
d3942a742d22: Pull complete 
2b95a7bc6bf9: Pull complete 
e4c7597bbbc1: Pull complete 
5f5ed4ce77dc: Pull complete 
63038208f189: Pull complete 
1138b1f02201: Pull complete 
f027013454f1: Pull complete 
41cf8eaed89c: Pull complete 
08038cdd003c: Pull complete 
d4afc280bba7: Pull complete 
a0416d3a601b: Pull complete 
173941a1f6c9: Pull complete 
Digest: sha256:830d6042fe2f936209efa041d6cbea6d6cfe4a8310d28f0048e8a80ed1b3b955

**Comment by reasonerjt** [comment] 2017-08-16 11:12
@ccnupq Thanks for reporting the issue.  Could you let us know on what version are you seeing such issue?  could you package the whole common/config directory so we can have a look at all your configuration files for different components?

Also please let me clarify, in your reproducing steps, how does step 1,2 and step 3 relevant?  Did you push a image to Harbor and try to pull it from another client and it failed?

Could you kindly test with some images that can be accessed on docker hub?

**Comment by ccnupq** [comment] 2017-08-16 11:50
@reasonerjt 

Could you let us know on what version are you seeing such issue? 
`[Answer] Harbor,v1.2.0-rc1-8-g87825c8`

could you package the whole common/config directory so we can have a look at all your configuration files for different components?
```
[Answer]  There are so much sensitive information in common/config.  
If I package them, i am not sure if I can clear all sensitive information.  
Would please let me know which specific file you need? So that i can handle one file every time.
Actually, I just install the Harbor as official instructions and configure https with our certificate.

ui_url_protocol = https
ssl_cert = /home/xxx/harbor_cert/registry.example.com.cer
ssl_cert_key = /home/xxx/harbor_cert/registry.example.com.key

No more other modification in common/config

```
Also please let me clarify, in your reproducing steps, how does step 1,2 and step 3 relevant? 
```
[Answer] My developer "docker login" and "docker push"  to Harbor on Server A .
Then my tester "docker login" and "docker pull" from Harbor  on Server B.
These are real normal actions.
```

Did you push a image to Harbor and try to pull it from another client and it failed?
```
[Answer]  Yes.  I tried push and pull from many different servers and different docker client.
All "docker push" can success. However all "docker pull"  failed as above.
I do not think is related with docker client or docker version.
```

Could you kindly test with some images that can be accessed on docker hub?
We'd like to reproduce it and investigate in our own env.
```
[Answer] I already tried some different images where built by our projects.  
All my images are good and there is no corruption because all push and pull works well if i try my images in my simple "Registry" environment  which is used by us before Harbor involved.

The smallest images is 124MB and the largest image is 1.3GB.  
All of them will "docker pull" fail if I use Harbor.

After i made this change in Nginx
   proxy_max_temp_file_size 0;
No issue was found any more.  
So i think this is a issue in Nginx configuration of Harbor.

```

**Comment by ccnupq** [comment] 2017-08-16 12:30
@reasonerjt   please check attached      Harbor.error.log_2017-08-16.txt  for error log.

**Comment by yixingjia** [comment] 2017-08-17 06:38
@ccnupq which user do you use to run the harbor?

it failed due to 
/etc//nginx/proxy_temp/6/14/0000000146" failed (13: Permission denied) while reading upstream

so when you try to pull an image it cannot write the buffer to the temp file.

you set proxy_max_temp_file_size 0 to make it works because it disable the buffer to temp file.

So please make sure the user you use have permission to the /etc/nginx directory.

**Comment by ccnupq** [comment] 2017-08-17 08:37
@yixingjia 

My Harbor is run with root user in the host server.

```
ps auxwww|grep harbor
root     47512  0.0  0.0 2268156 5344 ?        Ssl  Aug16   0:00 /harbor/harbor_adminserver
root     47787  0.0  0.0 3602668 20512 ?       Ssl  Aug16   0:22 /harbor/harbor_ui
root     47959  0.0  0.0 2824200 13396 ?       Ssl  Aug16   0:03 /harbor/harbor_jobservice

ps auxwww|grep nginx
root     48024  0.0  0.0  42704  6024 ?        Ss   Aug16   0:00 nginx: master process nginx -g daemon off;
nobody   48157  0.0  0.0  43136  3956 ?        S    Aug16   0:00 nginx: worker process
nobody   48158  0.0  0.0  43272  3956 ?        S    Aug16   0:00 nginx: worker process
...
```

In  Nginx container, I made test and the "root" of container have all permission in above directory.

```
docker exec -it nginx /bin/bash

root [ ~ ]# mkdir -p /etc//nginx/proxy_temp/6/14
root [ ~ ]# vim /etc//nginx/proxy_temp/6/14/0000000146
root [ ~ ]# cat /etc//nginx/proxy_temp/6/14/0000000146
Hello
root [ ~ ]# rm /etc//nginx/proxy_temp/6/14/0000000146
```

I am wondering why proxy log show "Permission denied".

**Comment by yixingjia** [comment] 2017-08-17 09:10
to fix the issue , you need to check the permission of the follow directory
./harbor/common/config/nginx/  that will map to the /etc/nginx in the docker container.

Close this as this is a file permission issue.

**Comment by yixingjia** [comment] 2017-08-17 09:16
I just setup and evn and it works as expected.
Can you please check the owner of the files under this nginx folder in Harbor server?

cd ./harbor/common/config/nginx
ls -all

drwxr-xr-x 9 root   root 4096 Aug 17 01:06 .
drwxr-xr-x 8 root   root 4096 Aug 17 01:06 ..
drwxr-xr-x 2 root   root 4096 Aug 17 01:06 cert
drwx------ 2 nobody root 4096 Aug 17 01:06 client_body_temp
drwxr-xr-x 2 root   root 4096 Aug 17 01:06 conf.d
drwx------ 2 nobody root 4096 Aug 17 01:06 fastcgi_temp
-rw-r--r-- 1 root   root 3162 Aug 17 01:06 nginx.conf
drwx------ 5 nobody root 4096 Aug 17 01:56 proxy_temp
drwx------ 2 nobody root 4096 Aug 17 01:06 scgi_temp
drwx------ 2 nobody root 4096 Aug 17 01:06 uwsgi_temp

by default the owner of the proxy_temp folder will nobody

**Comment by ccnupq** [comment] 2017-08-17 09:34
@yixingjia 

>/home/xxxx/gopath/src/github.com/vmware/harbor/make/common/config/nginx# ls -lrt

total 52
drwxr-xr-x 2 root   root 4096 Aug 11 22:05 conf.d
drwx------ 2 nobody root 4096 Aug 11 22:08 uwsgi_temp
drwx------ 2 nobody root 4096 Aug 11 22:08 scgi_temp
drwx------ 2 nobody root 4096 Aug 11 22:08 fastcgi_temp
drwxr-xr-x 2 root   root 4096 Aug 16 11:33 cert
drwxr-xr-x 2 root   root 4096 Aug 16 18:28 harbor_patch
drwx------ 2 nobody root 4096 Aug 17 14:45 client_body_temp
drwx------ 2 nobody root 4096 Aug 17 17:28 proxy_temp

**Comment by ccnupq** [comment] 2017-08-17 10:05
@yixingjia   I  think I hit bug  in Nginx

FYI.
https://www.ruby-forum.com/topic/179196

in the Nginx container: 
1.  cleared  out  proxy_temp   :    rm -rf /etc/nginx/proxy_temp/*
2.  remove "proxy_max_temp_file_size 0".  Keep all content as Nginx templates
3.  /usr/sbin/nginx -s reload

The issue was gone.  All docker pull work well.
I think the old content in /etc/nginx/proxy_temp/  could be corrupted by Nginx.

-----------------
Should it enable proxy buffer in Harbor?
Is it possible set  "proxy_max_temp_file_size 0" to avoid above issue?

**Comment by yixingjia** [comment] 2017-08-17 10:08
@ccnupq  you are not suggested to remove proxy_max_temp_file_size, since that will cause the pull image slow down.

**Comment by yixingjia** [comment] 2017-08-17 10:13
@ccnupq  I will close this bug as nothing need harbor do for this issue. Please feel free to reopen is if you have updates.

**Closed by yixingjia** 2017-08-17 10:13 UTC
Labels: kind/customer-found, priority/medium, target/1.2.0

**Comment by sonicning** [comment] 2017-08-30 12:16
hi @yixingjia @ccnupq I tried your solution and changed the owner of the proxy_temp folder to nobody . but I am still having this issue

**Comment by sonicning** [comment] 2017-08-30 12:27
btw, I used the workaround here https://github.com/vmware/harbor/issues/3086 and added this to the template , problem solved
proxy_temp_path /tmp/nginx_proxy/;

**Comment by ccnupq** [comment] 2017-08-30 12:28
There are two solutions above.   Which one do you try?  Please also paste your detailed error information and harbor log in /var/log/harbor/

**Comment by sonicning** [comment] 2017-08-30 13:03
@ccnupq same error infomation.   I tried all solutions above only the workaround works for me,  proxy_max_temp_file_size to 0. As you mentioned , pull image will slow down , i checked the https://github.com/vmware/harbor/issues/3086 and the PR https://github.com/vmware/harbor/pull/3112  so I added both changes to my template , and it worked

**Comment by yixingjia** [comment] 2017-08-31 04:04
@sonicning  There are some trick permission under the ~/harbor/common/config/nginx directory under some environment. so we change that to /tmp/ which has loose permission restrict.

**Comment by a393060727** [comment] 2020-10-14 03:47
版本harbor1.9
部署在阿里云上的镜像仓库，多台服务器到仓库获取镜像。
有一台pull成功，其他都失败。
1、
![image](https://user-images.githubusercontent.com/29500599/95941302-05d5d780-0e13-11eb-9f9a-0c636cec27e2.png)
2、
e7c96db7181b: Downloading [==================================================>]  2.747MB/2.747MB
f910a506b6cb: Downloading [==================================================>]     238B/238B
b6abafe80f63: Downloading [==================================================>]  54.93MB/54.93MB
9e4407c1757e: Download complete 
2a1965e05010: Download complete 
unexpected EOF

然后多台服务器都不能解决

**Comment by LoneWolf6383** [comment] 2022-07-29 19:50
Just close the current terminal session and execute the pull in new terminal. It works for me!.
