### ISSUE TITLE
UI and Jobservice can't connect to MySQL

### ISSUE THREAD

**Issue by frapposelli** [vmware/harbor#1771] opened 2017-03-23 23:10 UTC
Bug appeared today, looks like the mysql user configuration prevents connections from IPs that are created by docker networks.

This is from `ui.log`:

```
Mar 23 23:06:32 172.18.0.1 ui[366]: 2017-03-23T23:06:32Z [INFO] Config path: /etc/ui/app.conf
Mar 23 23:06:32 172.18.0.1 ui[366]: 2017-03-23T23:06:32Z [INFO] initializing configurations...
Mar 23 23:06:32 172.18.0.1 ui[366]: 2017-03-23T23:06:32Z [INFO] key path: /etc/ui/key
Mar 23 23:06:32 172.18.0.1 ui[366]: 2017-03-23T23:06:32Z [INFO] initializing client for adminserver http://adminserver ...
Mar 23 23:06:32 172.18.0.1 ui[366]: 2017-03-23T23:06:32Z [INFO] configurations initialization completed
Mar 23 23:06:32 172.18.0.1 ui[366]: 2017-03-23T23:06:32Z [INFO] initializing database: type-MySQL host-mysql port-3306 user-root database-registry
Mar 23 23:06:32 172.18.0.1 ui[366]: 2017-03-23T23:06:32Z [FATAL] [main.go:89]: failed to initialize database: register db Ping `default`, Error 1130: Host '172.18.0.6' is not allowed to connect to this MySQL server
Mar 23 23:06:32 172.18.0.1 ui[366]: [ORM]register db Ping `default`, Error 1130: Host '172.18.0.6' is not allowed to connect to this MySQL server
```

This is from `jobservice.log`:

```
Mar 23 23:06:00 172.18.0.1 jobservice[366]: [ORM]register db Ping `default`, Error 1130: Host '172.18.0.7' is not allowed to connect to this MySQL server
Mar 23 23:06:28 172.18.0.1 jobservice[366]: 2017-03-23T23:06:28Z [INFO] Config path: /etc/jobservice/app.conf
Mar 23 23:06:28 172.18.0.1 jobservice[366]: 2017-03-23T23:06:28Z [INFO] initializing configurations...
Mar 23 23:06:28 172.18.0.1 jobservice[366]: 2017-03-23T23:06:28Z [INFO] key path: /etc/jobservice/key
Mar 23 23:06:28 172.18.0.1 jobservice[366]: 2017-03-23T23:06:28Z [INFO] initializing client for adminserver http://adminserver ...
Mar 23 23:06:28 172.18.0.1 jobservice[366]: 2017-03-23T23:06:28Z [INFO] configurations initialization completed
Mar 23 23:06:28 172.18.0.1 jobservice[366]: 2017-03-23T23:06:28Z [INFO] initializing database: type-MySQL host-mysql port-3306 user-root database-registry
Mar 23 23:06:28 172.18.0.1 jobservice[366]: [ORM]register db Ping `default`, Error 1130: Host '172.18.0.7' is not allowed to connect to this MySQL server
Mar 23 23:06:28 172.18.0.1 jobservice[366]: 2017-03-23T23:06:28Z [FATAL] [main.go:42]: failed to initialize database: register db Ping `default`, Error 1130: Host '172.18.0.7' is not allowed to connect to this MySQL server
```

**Comment by reasonerjt** [comment] 2017-03-24 01:07
Did you modify the docker-compose.yml, there are two mysql, one for Harbor one for Notary.

**Comment by frapposelli** [comment] 2017-03-24 07:48
There are no substantial modifications, the errors are for connections to the Harbor DB, not Notary (which is working fine).

These are the yaml files:

`docker-compose.yml`:

```yaml
networks:
  harbor:
    external: false
services:
  adminserver:
    container_name: harbor-adminserver
    depends_on:
    - log
    env_file:
    - /data/harbor/common/config/adminserver/env
    image: vmware/harbor-adminserver:dev
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:1514
        tag: adminserver
    networks:
    - harbor
    restart: on-failure
    volumes:
    - /data/harbor/config/:/etc/adminserver/
    - /data/harbor/secretkey:/etc/adminserver/key
    - /data/harbor/:/data/
  jobservice:
    container_name: harbor-jobservice
    depends_on:
    - ui
    - adminserver
    env_file:
    - /data/harbor/common/config/jobservice/env
    image: vmware/harbor-jobservice:dev
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:1514
        tag: jobservice
    networks:
    - harbor
    restart: on-failure
    volumes:
    - /data/harbor/job_logs:/var/log/jobs
    - /data/harbor/common/config/jobservice/app.conf:/etc/jobservice/app.conf
    - /data/harbor/secretkey:/etc/jobservice/key
  log:
    container_name: harbor-log
    image: vmware/harbor-log:dev
    networks:
    - harbor
    ports:
    - 1514:514
    restart: on-failure
    volumes:
    - /var/log/harbor/:/var/log/docker/
  mysql:
    container_name: harbor-db
    depends_on:
    - log
    env_file:
    - /data/harbor/common/config/db/env
    image: vmware/harbor-db:dev
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:1514
        tag: mysql
    networks:
    - harbor
    restart: on-failure
    volumes:
    - /data/harbor/database:/var/lib/mysql
  proxy:
    container_name: nginx
    depends_on:
    - mysql
    - registry
    - ui
    - log
    image: nginx:1.11.5
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:1514
        tag: proxy
    networks:
    - harbor
    ports:
    - 8443:443
    restart: on-failure
    volumes:
    - /data/harbor/common/config/nginx:/etc/nginx
  registry:
    command:
    - serve
    - /etc/registry/config.yml
    container_name: registry
    depends_on:
    - log
    environment:
    - GODEBUG=netdns=cgo
    image: registry:2.6.0
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:1514
        tag: registry
    networks:
    - harbor
    restart: on-failure
    volumes:
    - /data/harbor/registry:/storage
    - /data/harbor/common/config/registry/:/etc/registry/
  ui:
    container_name: harbor-ui
    depends_on:
    - log
    - adminserver
    - registry
    env_file:
    - /data/harbor/common/config/ui/env
    image: vmware/harbor-ui:dev
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:1514
        tag: ui
    networks:
    - harbor
    restart: on-failure
    volumes:
    - /data/harbor/common/config/ui/app.conf:/etc/ui/app.conf
    - /data/harbor/common/config/ui/private_key.pem:/etc/ui/private_key.pem
    - /data/harbor/secretkey:/etc/ui/key
version: '2'
```

and `docker-compose.notary.yml`:

```yaml
networks:
  harbor-notary:
    external: false
  notary-mdb:
    external: false
  notary-sig:
    external: false
services:
  notary-db:
    command: mysqld --innodb_file_per_table
    container_name: notary-db
    environment:
    - TERM=dumb
    - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    image: mariadb:10.1.10
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:1514
        tag: notary-db
    networks:
      notary-mdb:
        aliases:
        - mysql
    volumes:
    - /data/harbor/common/config/notary/mysql-initdb.d:/docker-entrypoint-initdb.d
    - /data/harbor/notary-db:/var/lib/mysql
  notary-server:
    command: -c "/migrations/migrate.sh && notary-server -config=/config/server-config.json
      -logf=logfmt"
    container_name: notary-server
    depends_on:
    - notary-db
    - notary-signer
    entrypoint: /usr/bin/env sh
    image: vmware/notary-photon:server-0.5.0
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:1514
        tag: notary-server
    networks:
    - notary-mdb
    - notary-sig
    - harbor-notary
    volumes:
    - /data/harbor/common/config/notary:/config
  notary-signer:
    command: -c "/migrations/migrate.sh && notary-signer -config=/config/signer-config.json
      -logf=logfmt"
    container_name: notary-signer
    depends_on:
    - notary-db
    entrypoint: /usr/bin/env sh
    env_file:
    - /data/harbor/common/config/notary/signer_env
    image: vmware/notary-photon:signer-0.5.0
    logging:
      driver: syslog
      options:
        syslog-address: tcp://127.0.0.1:1514
        tag: notary-signer
    networks:
      notary-mdb: null
      notary-sig:
        aliases:
        - notarysigner
    volumes:
    - /data/harbor/common/config/notary:/config
  proxy:
    networks:
    - harbor-notary
  ui:
    networks:
    - harbor-notary
version: '2'
```

**Comment by frapposelli** [comment] 2017-03-27 13:04
more debug info, the same OVA deployed two times yields two different results, here's the situation of the `mysql.user` table in both deployments

working:

```
root@localhost [ ~ ]# docker exec -it harbor-db bash
root@230d53a47462:/tmp# mysql -uroot -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 5.6.34 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use mysql
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select host,user from user;
+------+------+
| host | user |
+------+------+
| %    | root |
+------+------+
1 row in set (0.00 sec)
```

not working:

```
root@localhost [ ~ ]# docker exec -it harbor-db bash
root@f923e547eb2c:/tmp# mysql -uroot
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 103
Server version: 5.6.34 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use mysql;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select host,user from user;
+--------------+------+
| host         | user |
+--------------+------+
| 0ff33d53999a |      |
| 0ff33d53999a | root |
| 127.0.0.1    | root |
| ::1          | root |
| localhost    |      |
| localhost    | root |
+--------------+------+
6 rows in set (0.00 sec)
```

**Comment by reasonerjt** [comment] 2017-03-28 05:48
@frapposelli please attach the mysql.log of both env, seems for second env the script in mysql container failed to run.

**Comment by frapposelli** [comment] 2017-03-28 08:36
@reasonerjt this is from the failed environment, it contains all the logs that harbor produces

[harbor-failed.tar.gz](https://github.com/vmware/harbor/files/874951/harbor-failed.tar.gz)

**Comment by frapposelli** [comment] 2017-04-05 21:15
another occurrence happened today, with the RC version of Harbor
[log.zip](https://github.com/vmware/harbor/files/900814/log.zip)

**Comment by reasonerjt** [comment] 2017-04-06 06:03
In the second logs, the root cause seems wrong password,  my guess is that it's usage error.

**Comment by reasonerjt** [comment] 2017-04-13 09:01
@frapposelli I'm closing this issue, feel free to re-open if you re-produce the issue.

**Closed by reasonerjt** 2017-04-13 09:01 UTC
