### ISSUE TITLE
Harbor configured with Static IP does not connect to LDAP (or not pinging to any other subnet)

### ISSUE THREAD

**Issue by mobla** [vmware/harbor#1138] opened 2016-11-22 02:36 UTC
Harbor Version: 0.5.0 RC1

1. OVA deploy of Harbor on VC/ESX 6.0 via C# client
2. Configure static IP with FQDN
Note: Domain name of this VM is not intuitive. Is this FQDN or partially QDN or just the suffix/domain name?
I assume it is a FQDN. See screenshot..
3. Failing to configure static network on Harbor (I think VAMI is failing)

![image](https://cloud.githubusercontent.com/assets/3538999/20500887/3fdb158c-afec-11e6-84cd-ed650d1e980f.png)

Attempt1
![image](https://cloud.githubusercontent.com/assets/3538999/20501145/73d8bc80-afed-11e6-8866-40c5d2d37d46.png)

Attempt2 (with DNS search path space separated - rest all same)
![image](https://cloud.githubusercontent.com/assets/3538999/20508662/ecf4d408-b017-11e6-8e1e-5286b4acc134.png)

Observations:
a. When the system boots (firstboot), I guess it uses VAMI to set the network? I SSH'ed and checked the following and it sets it correctly. But at the end, DNS gets messed up (may be going to fallback)

root@sc2-cpbu-vcsa01-6 [ ~ ]# /opt/vmware/share/vami/vami_dns
nameserver1 10.172.40.1
nameserver2 10.172.40.2
domain sc2-cpbu-vcsa01-6.eng.vmware.com
searchpath eng.vmware.com vmware.com

root@sc2-cpbu-vcsa01-6 [ ~ ]# /opt/vmware/share/vami/vami_get_network eth0
interface: eth0
config_present: true
config_flags: STATICV4
config_ipv4addr: 10.172.64.6
config_netmask: 255.255.255.192
config_broadcast: 10.172.64.63
config_gatewayv4: 10.172.64.62
config_ipv6addr:
config_prefix:
config_gatewayv6:
autoipv6:
active_ipv4addr: 10.172.64.6
active_netmask: 255.255.255.192
active_broadcast: 10.172.64.63
active_ipv6addr:
active_prefix:
active_gatewayv4: 10.172.64.62
active_gatewayv6:
hasdhcpv6: 1
managed: Managed Externally

root@sc2-cpbu-vcsa01-6 [ ~ ]# ping yahoo.com
PING yahoo.com (98.139.183.24) 56(84) bytes of data.
--- yahoo.com ping statistics ---
15 packets transmitted, 0 received, 100% packet loss, time 14110ms

root@sc2-cpbu-vcsa01-6 [ ~ ]# ip route
default via 10.172.64.62 dev eth0  proto static
10.172.64.0/26 dev eth0  proto kernel  scope link  src 10.172.64.6
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
172.18.0.0/16 dev br-d1605d46b9a8  proto kernel  scope link  src 172.18.0.1

root@sc2-cpbu-vcsa01-6 [ ~ ]# /opt/vmware/share/vami/vami_dns    -----> Post firstboot, DNS entries are messed
nameserver1 8.8.8.8
nameserver2 8.8.4.4
nameserver3 2001:4860:4860::8888
nameserver4 2001:4860:4860::8844

root@sc2-cpbu-vcsa01-6 [ ~ ]# hostname
sc2-cpbu-vcsa01-6.eng.vmware.com

root@sc2-cpbu-vcsa01-6 [ ~ ]# /opt/vmware/share/vami/vami_fullhostname
sc2-cpbu-vcsa01-6.eng.vmware.com

DNS servers are not setting properly (tried using VAMI CLI as well, but no luck!)
/opt/vmware/share/vami/vami_set_dns

LDAP is not working and from Harbor machine, it is not connecting (pinging) to machines on any other subnet!

**Comment by mobla** [comment] 2016-11-22 02:46
Logs

[config.tar.gz](https://github.com/vmware/harbor/files/605293/config.tar.gz)
[logs.tar.gz](https://github.com/vmware/harbor/files/605292/logs.tar.gz)

**Comment by ywk253100** [comment] 2016-11-22 03:53
Harbor can be visited but LDAP users can not login as the LDAP server can not be resolved correctly. This is the problem you encountered, right?

**Comment by mobla** [comment] 2016-11-22 04:43
Yes and also 
a. Harbor machine, it is not connecting (pinging) to machines on any other subnet!
b. Rebooting the machine resets the hostname to "localhost.localdom"

**Comment by mobla** [comment] 2016-11-22 05:01
![image](https://cloud.githubusercontent.com/assets/3538999/20511491/b8679962-b02d-11e6-8dcd-f4b2d3eda0d7.png)

**Comment by reasonerjt** [comment] 2016-11-22 10:39
@mobla 
For this case, we see the vami script was called to set the DNS correctly, but after that something messed up the network settings.

We believe the issue lies in the bootstrap process of photon OS, something maybe wrong in the VA studio for mis-configuration, a bug has been opened on bugzilla to track that, we are also investigating, if the root cause is not fixed we'll provide some work around for this particular scenario.

**Comment by ywk253100** [comment] 2016-11-28 03:24
Fixed by #1158 .

**Closed by ywk253100** 2016-11-28 03:24 UTC
