### ISSUE TITLE
[CI found] Get scan error for hello-world

### ISSUE THREAD

**Issue by wy65701436** [vmware/harbor#3131] opened 2017-08-30 03:07 UTC
![image](https://user-images.githubusercontent.com/2841473/29853572-4b836f78-8d73-11e7-9ca7-2e17af5ecf22.png)

The log path is:
https://storage.googleapis.com/harbor-ci-logs/integration_logs_593_c03f614ee3c85a06ace983277a827b073b2c9680.zip

**Comment by reasonerjt** [comment] 2017-09-20 10:07
Closing due to un-reproducible.

**Closed by reasonerjt** 2017-09-20 10:07 UTC
Labels: kind/automation-found
