### ISSUE TITLE
'Test LDAP Server' button does not work well

### ISSUE THREAD

**Issue by jessehu** [vmware/harbor#3653] opened 2017-11-21 10:38 UTC
After installing offline installer harbor.v1.2.0-229, login as 'admin', go to 'Administrator' -> 'Configuration' -> 'Authentication' Tab, select 'LDAP' Click 'Test LDAP Server', it reports error like "Auth Mode is not LDAP ..."
Expected: it should do the LDAP connection test

**Comment by steven-zou** [comment] 2017-11-22 07:25
Assigned to @ninjadq to fix.

**Comment by ninjadq** [comment] 2017-12-05 03:22
discussed with @steven-zou we think this may not a bug. Because you are editing LDAP config and these config not saved yet.

**Comment by mlh78750** [comment] 2017-12-06 14:39
If we're not fixing, then can we close this issue.

**Comment by reasonerjt** [comment] 2017-12-06 15:01
@mlh78750 we still need to discuss and confirm with the creator of this issue.

**Comment by mlh78750** [comment] 2017-12-06 15:41
I just saw the wontfix label. I'm fine either way, but if we decide we're not fixing, lets close the issue.

**Comment by reasonerjt** [comment] 2017-12-07 07:55
@stonezdj I think it's a bug in ping ldap api, please work with Jesse to investigate.

**Comment by reasonerjt** [comment] 2017-12-19 09:08
Fixed in #3796

**Closed by reasonerjt** 2017-12-19 09:08 UTC
Labels: area/ldap, kind/bug
