### ISSUE TITLE
The "Projects" table is misaligned

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/harbor#2140] opened 2017-04-25 17:36 UTC
In vSphere Integrated Containers mode, the projects table is misaligned. See below. 

![2-harbor](https://cloud.githubusercontent.com/assets/13806150/25398999/c175e06a-29a2-11e7-9d7c-e32716f5d9f4.png)

**Comment by lweitzman** [comment] 2017-04-25 17:42
are you saying the margin is too wide? this is what i'm seeing at https://10.112.122.204/harbor/projects
which seems correct.

![screen shot 2017-04-25 at 1 41 21 pm](https://cloud.githubusercontent.com/assets/626032/25399294/faf50ca2-29bc-11e7-83a2-9d2f6c1ea3e2.png)

**Comment by karthik-narayan** [comment] 2017-04-25 17:44
The right hand corner of row 3 & 4 are not aligned with the rest of the table. Please see my screenshot.

**Comment by akshayl** [comment] 2017-04-25 17:45
Dupe of #2064

**Closed by akshayl** 2017-04-25 17:45 UTC
Labels: area/clarity-ui, UX
