### ISSUE TITLE
clair container can not get up, the log shows: open / configure / config.yaml: permission denied "

### ISSUE THREAD

**Issue by jiananjiang** [vmware/harbor#3478] opened 2017-10-30 03:15 UTC
[root@centjiang 2017-10-30]# vim clair.log 

Oct 30 11:07:57 bogon clair[2644]: time="2017-10-30T03:07:57Z" level=fatal msg="failed to load configuration" error="open /config/config.yaml: permission denied"
Oct 30 11:08:06 bogon clair[2644]: time="2017-10-30T03:08:06Z" level=fatal msg="failed to load configuration" error="open /config/config.yaml: permission denied"
Oct 30 11:08:13 bogon clair[2644]: time="2017-10-30T03:08:13Z" level=fatal msg="failed to load configuration" error="open /config/config.yaml: permission denied"
Oct 30 11:08:23 bogon clair[2644]: time="2017-10-30T03:08:23Z" level=fatal msg="failed to load configuration" error="open /config/config.yaml: permission denied"

[root@centjiang jiangkeyu]# docker info
Containers: 12
 Running: 11
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-8890066-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 83.5 GB
 Data Space Total: 107.4 GB
 Data Space Available: 4.329 GB
 Metadata Space Used: 5.542 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 1
Total Memory: 992.6 MiB
Name: centjiang
ID: YM7C:DSSY:YHHE:GN7E:RCAH:JFRU:FIBY:H63Y:FPNM:WVHV:TLE5:RKJW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 192.168.56.103
 127.0.0.0/8
Registries: docker.io (secure)

**Comment by steven-zou** [comment] 2017-10-30 04:17
@ywk253100 

  Any thoughts? Wrong permission settings for that file?

**Comment by ywk253100** [comment] 2017-10-30 07:28
Duplicate of #3439. @jiananjiang Please refer to the issue.

**Closed by ywk253100** 2017-10-30 07:28 UTC
