### ISSUE TITLE
Harbor service cannot be started due to " Couldn't find env file: /etc/vmware/harbor/common/config/notary/signer_env"

### ISSUE THREAD

**Issue by lgayatri** [vmware/harbor#2983] opened 2017-08-07 09:39 UTC
Cred: root/Admin!23

Build: vic-4efc2f2e-dev.ova
After deploying the OVA, harbor service was unable to start.
Aug 07 09:37:09 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Control process exited, code=exited status=1
Aug 07 09:37:09 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Unit entered failed state.
Aug 07 09:37:09 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Failed with result 'exit-code'.
Aug 07 09:37:14 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Service hold-off time over, scheduling restart.
Aug 07 09:37:14 vic-st-h2-132.eng.vmware.com systemd[1]: Stopped Harbor Container Registry.
Aug 07 09:37:14 vic-st-h2-132.eng.vmware.com systemd[1]: Started Harbor Container Registry.
Aug 07 09:37:14 vic-st-h2-132.eng.vmware.com start_harbor.sh[28316]: Couldn't find env file: /etc/vmware/harbor/common/config/notary/signer_env
Aug 07 09:37:14 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Main process exited, code=exited, status=1/FAILURE
Aug 07 09:37:15 vic-st-h2-132.eng.vmware.com docker-compose[28380]: Couldn't find env file: /etc/vmware/harbor/common/config/notary/signer_env
Aug 07 09:37:15 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Control process exited, code=exited status=1
Aug 07 09:37:15 vic-st-h2-132.eng.vmware.com docker-compose[28406]: Couldn't find env file: /etc/vmware/harbor/common/config/notary/signer_env
Aug 07 09:37:15 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Control process exited, code=exited status=1
Aug 07 09:37:15 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Unit entered failed state.
Aug 07 09:37:15 vic-st-h2-132.eng.vmware.com systemd[1]: harbor.service: Failed with result 'exit-code'.

**Comment by wy65701436** [comment] 2017-08-07 12:43
@lgayatri could you just let me know the OVA build number?

**Comment by lgayatri** [comment] 2017-08-07 12:47
@wy65701436 Build: vic-4efc2f2e-dev.ova
https://storage.googleapis.com/vic-product-ova-builds/vic-4efc2f2e-dev.ova

**Comment by wy65701436** [comment] 2017-08-07 12:47
I will check with Andrew, see the build, ignore my last comment.

**Comment by andrewtchin** [comment] 2017-08-07 13:26
This should be closed as not a bug. 
PSC registration was not performed through the Getting Started page and user manually attempted to start Harbor without proper initialization

**Comment by reasonerjt** [comment] 2017-08-07 13:32
@lgayatri Before accessing Harbor or Admiral, did you login to the page at port :9443?  Admiral and harbor don't start until that happens.

**Comment by wy65701436** [comment] 2017-08-07 13:42
@lgayatri, can we just close it per Andrew's comment?

**Comment by lgayatri** [comment] 2017-08-07 13:50
After :9443 registration , it is the same error, I will redeploy and try.

**Comment by anchal-agrawal** [comment] 2017-08-07 15:46
@lgayatri The current steps for initializing the OVA are:

* Deploy via vSphere UI or ovftool
* Power on the appliance
* Visit `https://$OVA_IP:9443` (might be a few seconds before the server starts up) and enter vSphere credentials
* Admiral will start, then Harbor does
* Takes ~1 minute after entering vSphere credentials for Admiral and Harbor to fully initialize

These steps are briefly mentioned in our [user docs](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/deploy_vic_appliance.html), but I'll ensure that they're expanded upon so users don't have issues.

**No manual `systemd/systemctl` steps are needed and are strongly discouraged unless for development purposes.**

**Comment by lgayatri** [comment] 2017-08-08 06:58
After redeployment of OVA, I logged in :9443 and entered VCSA IP and cred. Got the Getting started page in couple of seconds
![image](https://user-images.githubusercontent.com/25006749/29059278-6b2a965a-7c32-11e7-9de1-2ac28c799f6c.png)
Waited for 20 minutes and checked :8282 
![image](https://user-images.githubusercontent.com/25006749/29059604-024c29e4-7c34-11e7-951f-88efe3490b11.png)
Please feel free to access the setup Live with usual creds

**Comment by lgayatri** [comment] 2017-08-08 13:48
On further debugging I found out that when OVA is deployed using ovftool command as below:

ovftool --overwrite --datastore=CPBU_2TB_01 --noSSLVerify --acceptAllEulas --name=vic-4efc2f2e-dev.ova   --net:Network="DPortGroup" --powerOn --X:injectOvfEnv --X:enableHiddenProperties --prop:appliance.root_pwd='Admin!23' --prop:appliance.permit_root_login=True  --prop:network.DNS=10.142.7.21 --prop:network.fqdn=vic-st-h2-132.eng.vmware.com --prop:network.gateway=10.197.37.253 --prop:network.ip0=10.197.37.132 --prop:network.netmask0=255.255.254.0 https://storage.googleapis.com/vic-product-ova-builds/vic-4efc2f2e-dev.ova  vi://administrator@vsphere.local:Admin\!23@10.197.37.191/Datacenter/host/Cluster

the services are NOT GETTING started.

Instead if I deploy manually then services are happily up in < 1 min. I will check the ovf properties and correct them.

**Comment by reasonerjt** [comment] 2017-08-09 04:20
Thanks for the update @lgayatri I'm closing the issue as the root cause is the approach to deploy the .ova.
And for further issues in this area please open issues on vmware/vic-product

**Closed by reasonerjt** 2017-08-09 04:20 UTC
Labels: target/1.2.0
