### ISSUE TITLE
Latest docker client not able to log into Harbor

### ISSUE THREAD

**Issue by tschwaller** [vmware/harbor#4142] opened 2018-01-26 14:59 UTC
When I try to log into Harbor from an Ubuntu 16.04.3 LTS host with `docker-ce 17.12.0` installed, I get the following error messages.

```
# docker login W.X.Y.Z
Username: administrator@vsphere.local
Password:
Error response from daemon: Get https://W.X.Y.Z/v2/: Get https://vic-tom.corp.local/service/token?account=administrator%40vsphere.local&client_id=docker&offline_token=true&service=harbor-registry: x509: certificate is not valid for any names, but wanted to match vic-tom.corp.local
# cd /etc/docker/certs.d
# ls
W.X.Y.Z  vic-tom.corp.local
# ls vic-tom.corp.local
ca.crt
# docker login vic-tom.corp.local
Username: administrator@vsphere.local
Password:
Error response from daemon: Get https://vic-tom.corp.local/v2/: x509: certificate is not valid for any names, but wanted to match vic-tom.corp.local
```

After I downgraded to `docker-ce 17.03.1` I could access the Harbor registry.

```
# apt-cache policy docker-ce
docker-ce:
  Installed: 17.03.1~ce-0~ubuntu-xenial
  Candidate: 17.12.0~ce-0~ubuntu
  Version table:
     17.12.0~ce-0~ubuntu 500
        500 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
     17.09.1~ce-0~ubuntu 500
        500 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
     17.09.0~ce-0~ubuntu 500
        500 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
     17.06.2~ce-0~ubuntu 500
        500 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
     17.06.1~ce-0~ubuntu 500
        500 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
     17.06.0~ce-0~ubuntu 500
        500 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
     17.03.2~ce-0~ubuntu-xenial 500
        500 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
 *** 17.03.1~ce-0~ubuntu-xenial 500
        500 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
        100 /var/lib/dpkg/status
     17.03.0~ce-0~ubuntu-xenial 500
        500 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
```

The last version which works is `docker-ce 17.09.1-ce`.

```
# docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

# docker login W.X.Y.Z
Username: administrator@vsphere.local
Password:
Login Succeeded
```

**Comment by reasonerjt** [comment] 2018-01-26 15:17
@tschwaller so this is a VIC installation?  We'll first try to reproduce with Harbor standalone installation. 
My gut feeling is that this has something to do with how the cert was generated.

@stonezdj Could you follow up?

**Comment by tschwaller** [comment] 2018-01-26 15:31
yes, this was a VIC installation using `vic-v1.3.0-3033-f8cc7317.ova`.

**Comment by tschwaller** [comment] 2018-01-26 18:44
Setting `export DOCKER_API_VERSION=1.13` (the one which is tested) with the latest `docker-ce` version does not resolve the issue.

**Comment by reasonerjt** [comment] 2018-01-29 11:24
Per investigation, the root cause is the way ova generates the certificate.
Moving this issue to https://github.com/vmware/vic-product/issues/1346

**Closed by reasonerjt** 2018-01-29 11:24 UTC
Labels: product/vic

**Comment by stonezdj** [comment] 2018-01-31 05:07
@tschwaller  the New VIC OVA build fixes this issue: https://storage.googleapis.com/vic-product-ova-builds/vic-stage-3304-v1.3.1-rc1-3304-3b3747a7.ova

**Comment by stuclem** [comment] 2018-01-31 09:43
If this only affects 1.3.0 and not 1.3.1, then I propose that we document it in the 1.3.0 release notes.
