### ISSUE TITLE
registry:runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zonesan** [vmware/harbor#617] opened 2016-08-01 08:52 UTC
This happens when I call api  /api/repositories/tags?repo_name=aaaaaaaa/bbbb

```html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>beego application error</title>
    <style>
        html, body, body * {padding: 0; margin: 0;}
        #header {background:#ffd; border-bottom:solid 2px #A31515; padding: 20px 10px;}
        #header h2{ }
        #footer {border-top:solid 1px #aaa; padding: 5px 10px; font-size: 12px; color:green;}
        #content {padding: 5px;}
        #content .stack b{ font-size: 13px; color: red;}
        #content .stack pre{padding-left: 10px;}
        table {}
        td.t {text-align: right; padding-right: 5px; color: #888;}
    </style>
    <script type="text/javascript">
    </script>
</head>
<body>
    <div id="header">
        <h2>registry:runtime error: invalid memory address or nil pointer dereference</h2>
    </div>
    <div id="content">
        <table>
            <tr>
                <td class="t">Request Method: </td><td>GET</td>
            </tr>
            <tr>
                <td class="t">Request URL: </td><td>/api/repositories/tags?repo_name=aaaaaaaa/bbbb</td>
            </tr>
            <tr>
                <td class="t">RemoteAddr: </td><td>2.2.2.2</td>
            </tr>
        </table>
        <div class="stack">
            <b>Stack</b>
            <pre>/usr/local/go/src/runtime/asm_amd64.s:472
/usr/local/go/src/runtime/panic.go:443
/usr/local/go/src/runtime/panic.go:62
/usr/local/go/src/runtime/sigpanic_unix.go:24
/usr/local/go/src/net/http/client.go:429
/usr/local/go/src/net/http/client.go:188
/go/src/github.com/vmware/harbor/utils/registry/repository.go:133
/go/src/github.com/vmware/harbor/api/repository.go:176
/usr/local/go/src/runtime/asm_amd64.s:472
/usr/local/go/src/reflect/value.go:435
/usr/local/go/src/reflect/value.go:303
/go/src/github.com/vmware/harbor/vendor/github.com/astaxie/beego/router.go:777
/usr/local/go/src/net/http/server.go:2081
/usr/local/go/src/net/http/server.go:1472
/usr/local/go/src/runtime/asm_amd64.s:1998
</pre>
        </div>
    </div>
    <div id="footer">
        <p>beego 1.6.0 (beego framework)</p>
        <p>golang version: go1.6.2</p>
    </div>
</body>
</html>
```

**Comment by ywk253100** [comment] 2016-08-01 09:03
Duplicate of #591 , and has been fix by #614 .

**Closed by ywk253100** 2016-08-01 09:03 UTC
