### ISSUE TITLE
When there is no 'latest' tag, the 'Deploy' button will trigger a 'add info' event

### ISSUE THREAD

**Issue by ninjadq** [vmware/harbor#4883] opened 2018-05-08 09:05 UTC
When there's no "latest" tag of the repo
the deploy button will be disabled and a tooltip will be shown to ask user set the "additional info"

**Comment by lweitzman** [comment] 2018-05-08 14:06
duplicate of #4788

**Comment by steven-zou** [comment] 2018-05-10 07:46
@lweitzman This one is not duplicated with #4788.
This one is used to track the work of disabling the 'DEPLOY' button when no `latest` tag existing
#4788 is to track the working of keeping consistent with Admiral UX

**Closed** 2018-05-30 08:39 UTC
Labels: UX, area/ui, product/vic, target/1.5.1
