### ISSUE TITLE
Deploy button style should consistent with admiral

### ISSUE THREAD

**Issue by ninjadq** [vmware/harbor#4841] opened 2018-05-02 08:34 UTC
This is our repo's cardview on Admiral

![image](https://user-images.githubusercontent.com/1069785/39513126-d352fbf8-4e25-11e8-9aad-c3256c091cce.png)

This is Admiral's public repositories' card

![image](https://user-images.githubusercontent.com/1069785/39513178-11119e4a-4e26-11e8-8798-e8692f5d384a.png)

Both wording and design style of the button are not consistent with Admiral. 

@lweitzman Could you redesign this page? thanks!

**Comment by lweitzman** [comment] 2018-05-02 14:32
dupe of 4788 closing

**Closed by lweitzman** 2018-05-02 14:32 UTC
